apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-wl
  namespace: argocd
spec:
  project: platform-system
  source:
    repoURL: https://github.com/rezakaramad/kubepave
    targetRevision: HEAD
    path: charts/gcp/traefik
    helm:
      valueFiles:
        - values-wl.yaml
  destination:
    name: in-cluster
    namespace: platform-system
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true

  # Below four resources are provided by GKE and should be ignored.
  ignoreDifferences:
    - group: apiextensions.k8s.io
      jsonPointers:
        - /spec
        - /metadata
      kind: CustomResourceDefinition
      name: httproutes.gateway.networking.k8s.io

    - group: apiextensions.k8s.io
      jsonPointers:
        - /spec
        - /metadata
      kind: CustomResourceDefinition
      name: gateways.gateway.networking.k8s.io

    - group: apiextensions.k8s.io
      jsonPointers:
        - /spec
        - /metadata
      kind: CustomResourceDefinition
      name: gatewayclasses.gateway.networking.k8s.io

    - group: apiextensions.k8s.io
      jsonPointers:
        - /spec
        - /metadata
      kind: CustomResourceDefinition
      name: referencegrants.gateway.networking.k8s.io

    - group: apiextensions.k8s.io
      jsonPointers:
        - /spec
        - /metadata
      kind: CustomResourceDefinition
      name: backendtlspolicies.gateway.networking.k8s.io
