{{- if .Values.entraIdProvider.enabled }}

apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azuread
spec:
  package: {{ .Values.entraIdProvider.providerPackage }}
  runtimeConfigRef:
    name: provider-azuread

{{- end }}
