apiVersion: v2
name: lgtm-grafana
description: Grafana operator with a Grafana instance, Mimir/Loki/Tempo datasources and Entra ID login.
version: 0.0.1
dependencies:
  - name: grafana-operator
    version: 5.25.0
    repository: https://grafana.github.io/helm-charts
