#!/usr/bin/env bash
set -euo pipefail

# Writes secrets from 'pass' into Vault for use by external-secrets.
#
# Differences from the minikube version:
#   - No update_hosts (systemd-resolved handles DNS)
#   - All vault commands run inside the pod to avoid CLI/server version mismatch
#   - register_clusters_argocd registers kind workload clusters (pull model)

DIR="$(cd "$(dirname "$0")" && pwd)"

# shellcheck source=libs/common.sh
source "$DIR/libs/common.sh"
# shellcheck source=libs/utils.sh
source "$DIR/libs/utils.sh"

# PowerDNS credentials are generated by setup-dns.sh and stored here
SECRETS_FILE="$REPO_ROOT/.powerdns.env"


# -----------------------------------------------------------------------------
# Vault helpers
# -----------------------------------------------------------------------------

# Write a KV v2 secret from key/value pairs.
# Handles multiline values (e.g. private keys) by building a JSON payload with
# Python3 and piping it into the pod over stdin.
#
# Usage: vault_kv_put PATH KEY VALUE [KEY VALUE ...]
vault_kv_put() {
  local path="$1"
  shift  # remaining args are alternating: key value key value ...

  local json
  json=$(python3 -c "
import json, sys
args = sys.argv[1:]
data = {}
for i in range(0, len(args), 2):
    data[args[i]] = args[i+1]
print(json.dumps(data))
" "$@")

  printf '%s' "$json" | \
    kubectl --context "$(kind_context management)" \
      -n "$VAULT_NAMESPACE" \
      exec -i vault-0 -- \
      sh -c "
        export VAULT_ADDR=http://127.0.0.1:8200
        export VAULT_TOKEN=\$(grep 'Initial Root Token:' /vault/data/init.txt | awk '{print \$4}')
        cat > /tmp/vkv.json
        vault kv put '$path' @/tmp/vkv.json
        rm -f /tmp/vkv.json
      "
}

# Run any vault command inside the pod
vault_exec() {
  kubectl --context "$(kind_context management)" \
    -n "$VAULT_NAMESPACE" \
    exec vault-0 -- \
    sh -c "
      export VAULT_ADDR=http://127.0.0.1:8200
      export VAULT_TOKEN=\$(grep 'Initial Root Token:' /vault/data/init.txt | awk '{print \$4}')
      $*
    "
}


# -----------------------------------------------------------------------------
# Root CA — push to Vault so any namespace can pull it via ExternalSecret
# -----------------------------------------------------------------------------
push_root_ca_to_vault() {
  log "Pushing root-ca into Vault..."

  local ca_crt tls_crt tls_key
  ca_crt=$(kubectl --context "$(kind_context management)" \
    -n "$PLATFORM_NAMESPACE" get secret root-ca \
    -o jsonpath='{.data.ca\.crt}' | base64 -d)
  tls_crt=$(kubectl --context "$(kind_context management)" \
    -n "$PLATFORM_NAMESPACE" get secret root-ca \
    -o jsonpath='{.data.tls\.crt}' | base64 -d)
  tls_key=$(kubectl --context "$(kind_context management)" \
    -n "$PLATFORM_NAMESPACE" get secret root-ca \
    -o jsonpath='{.data.tls\.key}' | base64 -d)

  vault_kv_put "local/shared/pki/root-ca" \
    "ca.crt"  "$ca_crt" \
    "tls.crt" "$tls_crt" \
    "tls.key" "$tls_key"

  ok "root-ca pushed to Vault at local/shared/pki/root-ca"
}


# -----------------------------------------------------------------------------
# GitHub App secret for Argo CD
# -----------------------------------------------------------------------------
create_github_app_secret_argocd() {
  log "Writing Argo CD GitHub App secrets..."

  log "Reading 'rezakaramad-argocd' GitHub App credentials from pass..."
  local app_id installation_id private_key
  app_id=$(pass show private/github/apps/rezakaramad-argocd/app-id | head -n1)
  installation_id=$(pass show private/github/apps/rezakaramad-argocd/installation-id | head -n1)
  private_key=$(pass show private/github/apps/rezakaramad-argocd/private-key)

  vault_kv_put "local/argocd/github/apps/rezakaramad" \
    "app-id"          "$app_id" \
    "installation-id" "$installation_id" \
    "private-key"     "$private_key"

  ok "ArgoCD GitHub App secret for rezakaramad written"

  log "Reading 'fluxdojo-argocd' GitHub App credentials from pass..."
  app_id=$(pass show private/github/apps/fluxdojo-argocd/app-id | head -n1)
  installation_id=$(pass show private/github/apps/fluxdojo-argocd/installation-id | head -n1)
  private_key=$(pass show private/github/apps/fluxdojo-argocd/private-key)

  vault_kv_put "local/argocd/github/apps/fluxdojo" \
    "app-id"          "$app_id" \
    "installation-id" "$installation_id" \
    "private-key"     "$private_key"

  ok "ArgoCD GitHub App secret for fluxdojo written"
}


# -----------------------------------------------------------------------------
# GitHub App secret for Crossplane
# -----------------------------------------------------------------------------
create_github_app_secret_crossplane() {
  log "Writing Crossplane GitHub App secrets..."

  log "Reading 'rezakaramad-crossplane' GitHub App credentials from pass..."
  local app_id installation_id private_key
  app_id=$(pass show private/github/apps/rezakaramad-crossplane/app-id | head -n1)
  installation_id=$(pass show private/github/apps/rezakaramad-crossplane/installation-id | head -n1)
  private_key=$(pass show private/github/apps/rezakaramad-crossplane/private-key)

  vault_kv_put "local/crossplane/github/apps/org-rezakaramad" \
    "app-id"          "$app_id" \
    "installation-id" "$installation_id" \
    "private-key"     "$private_key"

  ok "Crossplane GitHub App secret for rezakaramad written"

  log "Reading 'fluxdojo-crossplane' GitHub App credentials from pass..."
  app_id=$(pass show private/github/apps/fluxdojo-crossplane/app-id | head -n1)
  installation_id=$(pass show private/github/apps/fluxdojo-crossplane/installation-id | head -n1)
  private_key=$(pass show private/github/apps/fluxdojo-crossplane/private-key)

  vault_kv_put "local/crossplane/github/apps/org-fluxdojo" \
    "app-id"          "$app_id" \
    "installation-id" "$installation_id" \
    "private-key"     "$private_key"

  ok "Crossplane GitHub App secret for fluxdojo written"
}


# -----------------------------------------------------------------------------
# Azure AD App registration — Argo CD
# -----------------------------------------------------------------------------
create_argocd_app_registration_azure() {
  log "Writing ArgoCD Entra ID App secret..."

  local client_id tenant_id client_secret
  client_id=$(pass show private/azure/entraid/apps/argocd/client-id | head -n1)
  tenant_id=$(pass show private/azure/entraid/apps/tenant-id | head -n1)
  client_secret=$(pass show private/azure/entraid/apps/argocd/client-secrets/argocd/value | head -n1)

  vault_kv_put "local/argocd/azure/sso" \
    "client_id"     "$client_id" \
    "tenant_id"     "$tenant_id" \
    "client_secret" "$client_secret"

  ok "ArgoCD Entra ID client secret written"
}


# -----------------------------------------------------------------------------
# Azure AD App registration — Crossplane
# -----------------------------------------------------------------------------
create_crossplane_app_registration_azure() {
  log "Writing Crossplane Entra ID App secret..."

  local client_id tenant_id client_secret
  client_id=$(pass show private/azure/entraid/apps/crossplane/client-id | head -n1)
  tenant_id=$(pass show private/azure/entraid/apps/tenant-id | head -n1)
  client_secret=$(pass show private/azure/entraid/apps/crossplane/client-secrets/crossplane/value | head -n1)

  vault_kv_put "local/crossplane/azure" \
    "client_id"     "$client_id" \
    "tenant_id"     "$tenant_id" \
    "client_secret" "$client_secret"

  ok "Crossplane Entra ID client secret written"
}


# -----------------------------------------------------------------------------
# Keycloak credentials
# Pushed under local/keycloak/* so the keycloak chart's ExternalSecrets and
# the bootstrap Job (both using the `keycloak` SA, role `keycloak`) can read them.
# -----------------------------------------------------------------------------

# Returns 0 if a KV v2 secret already exists at the given path.
vault_kv_exists() {
  vault_exec "vault kv get '$1' >/dev/null 2>&1"
}

create_keycloak_secrets() {
  log "Writing Keycloak secrets to Vault..."

  # Entra ID app registration used by Keycloak for Azure SSO
  local client_id tenant_id client_secret
  client_id=$(pass show private/azure/entraid/apps/keycloak/client-id | head -n1)
  tenant_id=$(pass show private/azure/entraid/apps/tenant-id | head -n1)
  client_secret=$(pass show private/azure/entraid/apps/keycloak/client-secrets/keycloak/value | head -n1)

  vault_kv_put "local/keycloak/azure/apps/keycloak" \
    "client_id"     "$client_id" \
    "tenant_id"     "$tenant_id" \
    "client_secret" "$client_secret"

  ok "Keycloak Entra ID client secret written"

  # Admin user — generated once
  if vault_kv_exists "local/keycloak/admin"; then
    log "Keycloak admin secret already exists — skipping"
  else
    vault_kv_put "local/keycloak/admin" \
      "username" "admin" \
      "password" "$(openssl rand -hex 16)"
    ok "Keycloak admin credentials written"
  fi
}


# -----------------------------------------------------------------------------
# Argo CD workload cluster credentials (pull model)
# Creates an argocd-manager ServiceAccount with a long-lived token in each
# workload cluster and stores server + token in Vault. The argocd chart's
# clusters-credential ExternalSecret then materialises the ArgoCD cluster
# Secret so ArgoCD can connect out to the workload cluster.
#
# The ArgoCD cluster name is the kind context name (e.g. "kind-workload") and
# MUST match clusterCredentials[].name in argocd/values-local.yaml.
# -----------------------------------------------------------------------------
register_clusters_argocd() {
  log "Registering workload clusters with ArgoCD (pull model)..."

  get_kind_tenant_clusters | while read -r cluster; do
    local context name server token node_ip
    context="$(kind_context "$cluster")"
    name="$context"  # ArgoCD cluster name == kind context name

    log "Registering $name..."

    # ServiceAccount + cluster-admin binding for ArgoCD to manage the cluster
    kubectl --context "$context" -n kube-system \
      create serviceaccount argocd-manager \
      --dry-run=client -o yaml | kubectl --context "$context" apply -f -

    kubectl --context "$context" \
      create clusterrolebinding argocd-manager \
      --clusterrole=cluster-admin \
      --serviceaccount=kube-system:argocd-manager \
      --dry-run=client -o yaml | kubectl --context "$context" apply -f -

    # Long-lived (legacy) ServiceAccount token — avoids TokenRequest expiry
    kubectl --context "$context" -n kube-system apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: argocd-manager-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: argocd-manager
type: kubernetes.io/service-account-token
EOF

    # Wait for the token to be populated
    for _ in $(seq 1 15); do
      kubectl --context "$context" -n kube-system \
        get secret argocd-manager-token \
        -o jsonpath='{.data.token}' 2>/dev/null | grep -q . && break
      sleep 1
    done

    token=$(kubectl --context "$context" -n kube-system \
      get secret argocd-manager-token \
      -o jsonpath='{.data.token}' | base64 -d)

    # API server reachable from management pods via the kind Docker bridge
    node_ip=$(kubectl --context "$context" get node \
      -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
    server="https://${node_ip}:6443"

    log "  server: $server"

    vault_kv_put "local/argocd/clusters/${name}" \
      "server" "$server" \
      "token"  "$token"

    ok "$name registered in Vault"
  done
}


# -----------------------------------------------------------------------------
# PowerDNS credentials for external-dns
# Unlike minikube, we do NOT generate new keys here — PowerDNS is already
# running with the values in .powerdns.env. We push those exact values to
# Vault so baseline-management's ExternalSecret can materialise them.
# -----------------------------------------------------------------------------
create_powerdns_secrets() {
  log "Writing PowerDNS credentials to Vault..."

  if [[ ! -f "$SECRETS_FILE" ]]; then
    err "Secrets file not found: $SECRETS_FILE — run ./setup-dns.sh start first"
    return 1
  fi

  # shellcheck source=/dev/null
  source "$SECRETS_FILE"

  vault_kv_put "local/powerdns/db" \
    "user"     "pdns" \
    "password" "$POWERDNS_DB_PASSWORD"

  vault_kv_put "local/powerdns/api" \
    "key" "$POWERDNS_API_KEY"

  ok "PowerDNS credentials written"
}


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
main() {
  log "Waiting for Vault to be ready..."
  kubectl --context "$(kind_context management)" \
    -n "$VAULT_NAMESPACE" \
    wait pod vault-0 \
    --for=condition=Ready \
    --timeout=60s

  push_root_ca_to_vault
  create_github_app_secret_argocd
  create_github_app_secret_crossplane
  create_argocd_app_registration_azure
  create_crossplane_app_registration_azure
  create_keycloak_secrets
  register_clusters_argocd
  create_powerdns_secrets

  echo ""
  ok "All secrets written to Vault"
}

main "$@"
