#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"

# shellcheck source=libs/common.sh
source "$DIR/libs/common.sh"
# shellcheck source=libs/utils.sh
source "$DIR/libs/utils.sh"

ARGOCD_SERVER="argocd.mgmt.rezakara.demo:80"


# -----------------------------------------------------------------------------
# Wait for ArgoCD server to be reachable
# -----------------------------------------------------------------------------
wait_for_argocd() {
  log "Waiting for ArgoCD server..."

  for _ in {1..60}; do
    if curl -sf "http://argocd.mgmt.rezakara.demo/healthz" >/dev/null 2>&1; then
      ok "ArgoCD reachable at http://argocd.mgmt.rezakara.demo"
      return 0
    fi
    sleep 3
  done

  err "Timed out waiting for ArgoCD"
  exit 1
}


# -----------------------------------------------------------------------------
# Retrieve the initial admin password from the cluster secret
# -----------------------------------------------------------------------------
get_admin_password() {
  kubectl --context "$(kind_context management)" \
    -n "$ARGOCD_NAMESPACE" \
    get secret argocd-initial-admin-secret \
    -o jsonpath='{.data.password}' | base64 -d
}


# -----------------------------------------------------------------------------
# Log in to ArgoCD CLI
# -----------------------------------------------------------------------------
argocd_login() {
  local password
  password="$(get_admin_password)"

  log "Logging in to ArgoCD..."

  argocd login "$ARGOCD_SERVER" \
    --username admin \
    --password "$password" \
    --http-retry-max 3 \
    --insecure \
    --plaintext

  ok "Logged in"
}


# -----------------------------------------------------------------------------
# Register the workload cluster with ArgoCD (push model).
# Uses the kind kubeconfig context directly — no need to expose the API server
# externally since management pods can reach workload nodes via the kind bridge.
# -----------------------------------------------------------------------------
register_workload_cluster() {
  log "Registering workload cluster with ArgoCD..."

  if argocd cluster get "$(kind_context workload)" >/dev/null 2>&1; then
    ok "Workload cluster already registered"
    return
  fi

  argocd cluster add "$(kind_context workload)" \
    --name workload \
    --yes

  ok "Workload cluster registered"

  argocd cluster list
}


# -----------------------------------------------------------------------------
# Write admin credentials to .platform.env for convenience
# -----------------------------------------------------------------------------
save_credentials() {
  local password
  password="$(get_admin_password)"

  local creds_file="$REPO_ROOT/.platform.env"

  cat > "$creds_file" <<EOF
# Auto-generated by setup-argocd.sh — DO NOT COMMIT
export ARGOCD_SERVER="http://argocd.mgmt.rezakara.demo"
export ARGOCD_ADMIN_PASSWORD="${password}"
EOF

  chmod 600 "$creds_file"
  ok "Credentials saved to $creds_file"
  echo "  source .platform.env"
}


main() {
  wait_for_argocd
  argocd_login
  register_workload_cluster
  save_credentials
}

case "${1:-setup}" in
  setup)    main ;;
  password) get_admin_password && echo ;;
  *)
    echo "Usage: $0 [setup|password]"
    exit 1
    ;;
esac
