#!/usr/bin/env bash
set -euo pipefail

#-----------------------------------------------------------------------------
# setup-secrets.sh
# Writes secrets from 'pass' into OpenBao for use by external-secrets.
#
# Differences from the minikube version:
#   - No 'update_hosts' (systemd-resolved handles DNS)
#   - All bao commands run inside the pod to avoid CLI/server version mismatch
#   - 'register_clusters_argocd' registers kind development clusters (pull model)
#
# All platform secrets are written into the OpenBao `platform` namespace under
# the `kv` KV v2 mount (paths `kv/<component>/*`), matching the Pattern X
# topology configured by the openbao chart postStart hook and setup-openbao.sh.
# -----------------------------------------------------------------------------

# Set the script directory to the current file's directory
DIR="$(cd "$(dirname "$0")" && pwd)"

# Import common functions and variables
source "$DIR/libs/common.sh"
source "$DIR/libs/utils.sh"

# PowerDNS credentials are generated by setup-dns.sh and stored in the shared file
SECRETS_FILE="$REPO_ROOT/.platform.env"


# -----------------------------------------------------------------------------
# OpenBao helpers
# -----------------------------------------------------------------------------

# Write a KV v2 secret from key/value pairs into the OpenBao `platform`
# namespace. Handles multiline values (e.g. private keys) by building a JSON
# payload with Python3 and piping it into the pod over stdin.
#
# Usage: bao_kv_put PATH KEY VALUE [KEY VALUE ...]
bao_kv_put() {
  # Function arguments:
  #   $1: path in OpenBao (e.g. kv/shared/pki/root-ca)
  #   $2: first key
  #   $3: first value
  #   $4: second key (optional)
  #   $5: second value (optional)
  local path="$1"
  shift  # remaining args are alternating: key value key value ...

  # Build a JSON object from the key/value pairs using Python3 and pipe it into the OpenBao pod
  local json
  json=$(python3 -c "
import json, sys
args = sys.argv[1:]
data = {}
for i in range(0, len(args), 2):
    data[args[i]] = args[i+1]
print(json.dumps(data))
" "$@")

  # Pipe the JSON into the OpenBao pod and write it to the specified path using 'bao kv put'
  printf '%s' "$json" | \
    kubectl --context "$(kind_context management)" \
      -n "$OPENBAO_NAMESPACE" \
      exec -i openbao-0 -- \
      sh -c "
        export BAO_ADDR=http://127.0.0.1:8200
        export BAO_TOKEN=\$(grep 'Initial Root Token:' /openbao/data/init.txt | awk '{print \$4}')
        export BAO_NAMESPACE=platform
        cat > /tmp/vkv.json
        bao kv put '$path' @/tmp/vkv.json
        rm -f /tmp/vkv.json
      "
}

# Run any bao command inside the pod (platform namespace)
bao_exec() {
  kubectl --context "$(kind_context management)" \
    -n "$OPENBAO_NAMESPACE" \
    exec openbao-0 -- \
    sh -c "
      export BAO_ADDR=http://127.0.0.1:8200
      export BAO_TOKEN=\$(grep 'Initial Root Token:' /openbao/data/init.txt | awk '{print \$4}')
      export BAO_NAMESPACE=platform
      $*
    "
}


# -----------------------------------------------------------------------------
# Push 'root-ca' to OpenBao so any namespace can pull it via ExternalSecret
# -----------------------------------------------------------------------------
push_root_ca_to_vault() {
  log "Pushing root-ca into OpenBao..."

  # Read the root CA from the management cluster's 'root-ca' secret
  local ca_crt tls_crt tls_key
  ca_crt=$(kubectl --context "$(kind_context management)" \
    -n "$PLATFORM_NAMESPACE" get secret root-ca \
    -o jsonpath='{.data.ca\.crt}' | base64 -d)
  tls_crt=$(kubectl --context "$(kind_context management)" \
    -n "$PLATFORM_NAMESPACE" get secret root-ca \
    -o jsonpath='{.data.tls\.crt}' | base64 -d)
  tls_key=$(kubectl --context "$(kind_context management)" \
    -n "$PLATFORM_NAMESPACE" get secret root-ca \
    -o jsonpath='{.data.tls\.key}' | base64 -d)

  # Write the root CA and TLS cert/key to OpenBao under kv/shared/pki/root-ca
  bao_kv_put "kv/shared/pki/root-ca" \
    "ca.crt"  "$ca_crt" \
    "tls.crt" "$tls_crt" \
    "tls.key" "$tls_key"

  ok "root-ca pushed to OpenBao at kv/shared/pki/root-ca"
}


# -----------------------------------------------------------------------------
# GitHub App secret for Argo CD
# -----------------------------------------------------------------------------
create_github_app_secret_argocd() {
  log "Writing Argo CD GitHub App secrets..."

  log "Reading 'rezakaramad-argocd' GitHub App credentials from pass..."
  local app_id installation_id private_key
  app_id=$(pass show private/github/apps/rezakaramad-argocd/app-id | head -n1)
  installation_id=$(pass show private/github/apps/rezakaramad-argocd/installation-id | head -n1)
  private_key=$(pass show private/github/apps/rezakaramad-argocd/private-key)

  bao_kv_put "kv/argocd/github/apps/rezakaramad" \
    "app-id"          "$app_id" \
    "installation-id" "$installation_id" \
    "private-key"     "$private_key"

  ok "ArgoCD GitHub App secret for rezakaramad written"

  log "Reading 'talktorubberduckdev-argocd' GitHub App credentials from pass..."
  app_id=$(pass show private/github/apps/talktorubberduckdev-argocd/app-id | head -n1)
  installation_id=$(pass show private/github/apps/talktorubberduckdev-argocd/installation-id | head -n1)
  private_key=$(pass show private/github/apps/talktorubberduckdev-argocd/private-key)

  bao_kv_put "kv/argocd/github/apps/talktorubberduckdev" \
    "app-id"          "$app_id" \
    "installation-id" "$installation_id" \
    "private-key"     "$private_key"

  ok "ArgoCD GitHub App secret for talktorubberduckdev written"
}


# -----------------------------------------------------------------------------
# GitHub App secret for Crossplane
# -----------------------------------------------------------------------------
create_github_app_secret_crossplane() {
  log "Writing Crossplane GitHub App secrets..."

  log "Reading 'rezakaramad-crossplane' GitHub App credentials from pass..."
  local app_id installation_id private_key
  app_id=$(pass show private/github/apps/rezakaramad-crossplane/app-id | head -n1)
  installation_id=$(pass show private/github/apps/rezakaramad-crossplane/installation-id | head -n1)
  private_key=$(pass show private/github/apps/rezakaramad-crossplane/private-key)

  bao_kv_put "kv/crossplane/github/apps/org-rezakaramad" \
    "app-id"          "$app_id" \
    "installation-id" "$installation_id" \
    "private-key"     "$private_key"

  ok "Crossplane GitHub App secret for rezakaramad written"

  log "Reading 'talktorubberduckdev-crossplane' GitHub App credentials from pass..."
  app_id=$(pass show private/github/apps/talktorubberduckdev-crossplane/app-id | head -n1)
  installation_id=$(pass show private/github/apps/talktorubberduckdev-crossplane/installation-id | head -n1)
  private_key=$(pass show private/github/apps/talktorubberduckdev-crossplane/private-key)

  bao_kv_put "kv/crossplane/github/apps/org-talktorubberduckdev" \
    "app-id"          "$app_id" \
    "installation-id" "$installation_id" \
    "private-key"     "$private_key"

  ok "Crossplane GitHub App secret for talktorubberduckdev written"
}


# -----------------------------------------------------------------------------
# Azure AD App registration for Argo CD
# -----------------------------------------------------------------------------
create_argocd_app_registration_azure() {
  log "Writing ArgoCD Entra ID App secret..."

  local client_id tenant_id client_secret
  client_id=$(pass show private/azure/entraid/apps/argocd/client-id | head -n1)
  tenant_id=$(pass show private/azure/entraid/apps/tenant-id | head -n1)
  client_secret=$(pass show private/azure/entraid/apps/argocd/client-secrets/argocd/value | head -n1)

  bao_kv_put "kv/argocd/azure/sso" \
    "client_id"     "$client_id" \
    "tenant_id"     "$tenant_id" \
    "client_secret" "$client_secret"

  ok "ArgoCD Entra ID client secret written"
}


# -----------------------------------------------------------------------------
# Azure AD App registration for Crossplane
# -----------------------------------------------------------------------------
create_crossplane_app_registration_azure() {
  log "Writing Crossplane Entra ID App secret..."

  local client_id tenant_id client_secret
  client_id=$(pass show private/azure/entraid/apps/crossplane/client-id | head -n1)
  tenant_id=$(pass show private/azure/entraid/apps/tenant-id | head -n1)
  client_secret=$(pass show private/azure/entraid/apps/crossplane/client-secrets/crossplane/value | head -n1)

  bao_kv_put "kv/crossplane/azure" \
    "client_id"     "$client_id" \
    "tenant_id"     "$tenant_id" \
    "client_secret" "$client_secret"

  ok "Crossplane Entra ID client secret written"
}


# -----------------------------------------------------------------------------
# Keycloak credentials
# Pushed under kv/keycloak/* so the keycloak chart's ExternalSecrets and
# the bootstrap Job (both using the `keycloak` SA, role `keycloak`) can read them.
# -----------------------------------------------------------------------------

# Returns 0 if a KV v2 secret already exists at the given path.
bao_kv_exists() {
  bao_exec "bao kv get '$1' >/dev/null 2>&1"
}

create_keycloak_secrets() {
  log "Writing Keycloak secrets to OpenBao..."

  # Entra ID app registration used by Keycloak for Azure SSO
  local client_id tenant_id client_secret
  client_id=$(pass show private/azure/entraid/apps/keycloak/client-id | head -n1)
  tenant_id=$(pass show private/azure/entraid/apps/tenant-id | head -n1)
  client_secret=$(pass show private/azure/entraid/apps/keycloak/client-secrets/keycloak/value | head -n1)

  bao_kv_put "kv/keycloak/azure/apps/keycloak" \
    "client_id"     "$client_id" \
    "tenant_id"     "$tenant_id" \
    "client_secret" "$client_secret"

  ok "Keycloak Entra ID client secret written"

  # Admin user — generated once
  if bao_kv_exists "kv/keycloak/admin"; then
    log "Keycloak admin secret already exists — skipping"
  else
    bao_kv_put "kv/keycloak/admin" \
      "username" "admin" \
      "password" "$(openssl rand -hex 16)"
    ok "Keycloak admin credentials written"
  fi
}


# -----------------------------------------------------------------------------
# Argo CD development cluster credentials (pull model)
# Creates an 'argocd-manager' ServiceAccount with a long-lived token in each
# development cluster and stores server + token in OpenBao. The argocd chart's
# 'clusters-credential' ExternalSecret then materialises the ArgoCD cluster
# Secret so ArgoCD can connect out to the development cluster.
#
# The ArgoCD cluster name is the kind context name (e.g. 'kind-development') and
# MUST match 'clusterCredentials[].name' in 'argocd/values-local.yaml'.
# -----------------------------------------------------------------------------
register_clusters_argocd() {
  log "Registering development clusters with ArgoCD (pull model)..."

  get_kind_tenant_clusters | while read -r cluster; do
    local context name server token node_ip
    context="$(kind_context "$cluster")"
    name="$context"  # ArgoCD cluster name == kind context name

    log "Registering $name..."

    # ServiceAccount + cluster-admin binding for ArgoCD to manage the cluster
    kubectl --context "$context" -n kube-system \
      create serviceaccount argocd-manager \
      --dry-run=client -o yaml | kubectl --context "$context" apply -f -

    kubectl --context "$context" \
      create clusterrolebinding argocd-manager \
      --clusterrole=cluster-admin \
      --serviceaccount=kube-system:argocd-manager \
      --dry-run=client -o yaml | kubectl --context "$context" apply -f -

    # Long-lived (legacy) ServiceAccount token — avoids TokenRequest expiry
    kubectl --context "$context" -n kube-system apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: argocd-manager-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: argocd-manager
type: kubernetes.io/service-account-token
EOF

    # Wait for the token to be populated
    for _ in $(seq 1 15); do
      kubectl --context "$context" -n kube-system \
        get secret argocd-manager-token \
        -o jsonpath='{.data.token}' 2>/dev/null | grep -q . && break
      sleep 1
    done

    token=$(kubectl --context "$context" -n kube-system \
      get secret argocd-manager-token \
      -o jsonpath='{.data.token}' | base64 -d)

    # API server reachable from management pods via the kind Docker bridge
    node_ip=$(kubectl --context "$context" get node \
      -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
    server="https://${node_ip}:6443"

    log "  server: $server"

    bao_kv_put "kv/argocd/clusters/${name}" \
      "server" "$server" \
      "token"  "$token"

    ok "$name registered in OpenBao"
  done
}


# -----------------------------------------------------------------------------
# PowerDNS credentials for external-dns
# Unlike minikube, we do NOT generate new keys here — PowerDNS is already
# running with the values in .platform.env. We push those exact values to
# OpenBao so baseline-management's ExternalSecret can materialise them.
# -----------------------------------------------------------------------------
create_powerdns_secrets() {
  log "Writing PowerDNS credentials to OpenBao..."

  if [[ ! -f "$SECRETS_FILE" ]]; then
    err "Secrets file not found: $SECRETS_FILE — run ./setup-dns.sh start first"
    return 1
  fi

  # shellcheck source=/dev/null
  source "$SECRETS_FILE"

  bao_kv_put "kv/powerdns/db" \
    "user"     "pdns" \
    "password" "$POWERDNS_DB_PASSWORD"

  bao_kv_put "kv/powerdns/api" \
    "key" "$POWERDNS_API_KEY"

  ok "PowerDNS credentials written"
}


# -----------------------------------------------------------------------------
# Backstage — Entra ID app registration credentials
# Pushed under kv/backstage/* so the backstage chart's ExternalSecret
# (using the `backstage` SA, role `backstage`) can read them.
# -----------------------------------------------------------------------------
create_backstage_secrets() {
  log "Writing Backstage secrets to OpenBao..."

  local client_id client_secret tenant_id
  client_id=$(pass show private/azure/entraid/apps/backstage/client-id | head -n1)
  tenant_id=$(pass show private/azure/entraid/apps/tenant-id | head -n1)
  client_secret=$(pass show private/azure/entraid/apps/backstage/client-secrets/backstage/value | head -n1)

  bao_kv_put "kv/backstage/azure/app" \
    "client_id"     "$client_id" \
    "tenant_id"     "$tenant_id" \
    "client_secret" "$client_secret"

  # Generate a random 32-character cookie secret for oauth2-proxy AES-256 session
  # encryption. token_urlsafe(24) produces exactly 32 URL-safe characters.
  local cookie_secret
  cookie_secret=$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))')

  bao_kv_put "kv/backstage/oauth2-proxy" \
    "cookie_secret" "$cookie_secret"

  # Backstage Catalog Sync — reads users/groups from Entra ID into the catalog
  local sync_client_id sync_client_secret
  sync_client_id=$(pass show private/azure/entraid/apps/backstage-catalog-sync/client-id | head -n1)
  sync_client_secret=$(pass show private/azure/entraid/apps/backstage-catalog-sync/client-secrets/backstage-catalog-sync/value | head -n1)

  bao_kv_put "kv/backstage/msgraph/app" \
    "client_id"     "$sync_client_id" \
    "tenant_id"     "$tenant_id" \
    "client_secret" "$sync_client_secret"

  ok "Backstage secrets written (SSO app + oauth2-proxy cookie secret + catalog sync app)"
}


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
main() {
  log "Waiting for OpenBao to be ready..."
  kubectl --context "$(kind_context management)" \
    -n "$OPENBAO_NAMESPACE" \
    wait pod openbao-0 \
    --for=condition=Ready \
    --timeout=60s

  push_root_ca_to_vault
  create_github_app_secret_argocd
  create_github_app_secret_crossplane
  create_argocd_app_registration_azure
  create_crossplane_app_registration_azure
  create_keycloak_secrets
  create_backstage_secrets
  register_clusters_argocd
  create_powerdns_secrets

  echo ""
  ok "All secrets written to OpenBao"
}

main "$@"
