# --------------------------------------------------------------
# Azure AD and Entra ID configuration
azure:
  # principalType determines which Entra principal kind is assigned to AppRoles.
  # Use "user" when the function must provision a tenant user, or "group" when it should provision a group.
  # This is due to free tier Entra ID not supporting group-based assignment, so we use users in free tier and groups in enterprise tier.
  principalType: group

# --------------------------------------------------------------
# Tenant configuration
tenant:
  name: ""
  dnsName: ""

  argocd:

    # Application identity in Microsoft Entra ID.
    # You can find this in the Azure portal under Azure Active Directory > App registrations
    # These are persistent and should not be changed unless you are using a different Argo CD instance with a different service principal.
    identity:
      entraID:
        appObjectId: "113c7f42-c868-43cf-a1d2-121cd0b07763"
        servicePrincipalObjectId: "94ed43de-b44a-4174-a093-e3f78cd38b1e"

  # -----------------------------------
  # WHAT (permissions)
  roles:
    - name: admin
      policies:
        - resource: applications
          actions:
            - get
            - update
            - delete
            - sync
            - action/apps/Deployment/pause
            - action/apps/Deployment/resume
            - action/apps/Deployment/restart
            - action/batch/CronJob/create-job
        - resource: logs
          actions:
            - get

  # -----------------------------------
  # WHO and WHERE (assignment + Entra ID binding)
  bindings:
    - role: admin
      cluster: minikube-workload
      environmentPrefix: wl

      entraID:
        appRoleUUID: "00000000-0000-0000-0000-000000000001"

        assignment:
          # populated at deploy time via Crossplane function
          principalObjectId: ""
