tenant:
  name: ""
  dnsName: ""
  argocd:
    aadGroupId: ""

azure:
  freeTier: true

argocd:
  entraAppId: "6ebc7a2a-0d2c-4677-aebc-2b37371aca73"
  clusters:
    - clusterName: minikube-workload
      environmentPrefix: wl
      tenantAppProject:
        policies:
          - resource: applications
            actions:
              - get
              - update
              - delete
              - sync
              - action/apps/Deployment/pause
              - action/apps/Deployment/resume
              - action/apps/Deployment/restart
              - action/batch/CronJob/create-job
          - resource: logs
            actions:
              - get
        entraIDAppRoles:
          - name: admin
            description: Administrator role permits any action on any resource within the project.
            # An AppRole can be assigned to a user or group in Azure AD. The "assign" section defines how the AppRole should be assigned.
            assign:
              # The "principalObjectIdSelector" is used to select the user or group to which the AppRole will be assigned. 
              # In this case, it is disabled, and a specific principalObjectId can be provided if needed.
              principalObjectIdSelector:
                enabled: false
              # If "principalObjectIdSelector" is disabled, you can directly specify the "principalObjectId" of the user or group
              # to which the AppRole should be assigned.
              principalObjectId: ""
