tenant:
  name: ""
  dnsName: ""

  rbac:
    entraArgoCDAppObjectId: "113c7f42-c868-43cf-a1d2-121cd0b07763"
    entraArgoCDServicePrincipalObjectId: "94ed43de-b44a-4174-a093-e3f78cd38b1e"

    # Define roles and their corresponding permissions. 
    # Each role can have multiple policies that specify the resources and actions allowed for that role.
    # Assignments define how the AppRole is assigned to users or groups in Azure AD.
    #   In free tier, we're limited to users only, so we can disable the selector and directly specify principalObjectIds.
    #   In enterprise tier, you can enable the selector to dynamically assign the role based on user or group attributes.
    #   if enabled, it automatically assigns the role to the group that matches the tenant name, role name, and cluster environment prefix.
    #   E.g. for tenant "acme", role "admin", and cluster environment prefix "prod",
    #     it would look for a group with the name "acme-admin-prod" and assign the role to that group.
    # If the selector is disabled, you directly specify the principal object IDs (users or groups) that should be assigned to the role.
    # In enterprise tier, users will no longer be needed for role assignments.
    # 
    # We create one AppRole per role (admin, viewer) per environment (dev, staging, prod) to allow for granular access control.
    # This means that if you have 2 roles and 3 environments, you'll end up with 6 AppRoles in total 
    # (e.g., foo-admin-dev, foo-admin-staging, foo-admin-prod, foo-viewer-dev, foo-viewer-staging, foo-viewer-prod).

    roles:
      - name: admin
        instances:
          - cluster: minikube-workload
            environmentPrefix: wl
            entraID:
              appRoleUUID: "00000000-0000-0000-0000-000000000001"
              assignment:
                principalObjectIdSelector:
                  enabled: false
                # principalObjectIds:
                #   - "ee16a472-e5bd-4f24-9cfe-cb22429b11c4"
        policies:
          - resource: applications
            actions:
              - get
              - update
              - delete
              - sync
              - action/apps/Deployment/pause
              - action/apps/Deployment/resume
              - action/apps/Deployment/restart
              - action/batch/CronJob/create-job
          - resource: logs
            actions:
              - get

      - name: viewer
        instances:
          - cluster: minikube-workload
            environmentPrefix: wl
            entraID:
              appRoleUUID: "00000000-0000-0000-0000-000000000002"
              assignment:
                principalObjectIdSelector:
                  enabled: false
                # principalObjectIds:
                #   - "ee16a472-e5bd-4f24-9cfe-cb22429b11c4"
        policies:
          - resource: applications
            actions:
              - get
          - resource: logs
            actions:
              - get

# --------------------------------------------------------------
# Azure AD and Entra ID configuration
azure:
  # This flag indicates whether the tenant is using the free tier of Azure AD or the enterprise tier.
  # In free tier, we have limitations such as no group-based role assignments, so we need to directly assign roles to users.
  # In enterprise tier, we can leverage groups and dynamic assignments.
  freeTier: true
