{{- range $binding := $.Values.tenant.bindings }}

{{- $role := include "tenant.roleByName" (dict "roles" $.Values.tenant.roles "name" $binding.role) | fromYaml }}
{{- if not $role }}
{{- fail (printf "Role '%s' not defined in tenant.roles" $binding.role) }}
{{- end }}

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "{{ $.Values.tenant.name }}-{{ $binding.role }}-{{ $binding.environmentPrefix }}"

  namespace: argocd
  labels:
  {{ include "common.labels" . | nindent 4 }}
    platform.rezakara.demo/tenant: "{{ $.Values.tenant.name | lower }}"
    platform.rezakara.demo/cluster: "{{ $binding.cluster | lower }}"
    platform.rezakara.demo/role: "{{ $binding.role | lower }}"
spec:
  description: Argo CD AppProject for {{ $.Values.tenant.name }} ({{ $binding.role }} in {{ $binding.cluster }})

  sourceNamespaces:
    - "gitops-{{ $.Values.tenant.name }}"

  sourceRepos:
    - {{ include "tenant.repoURL" $.Values.tenant.name | quote }}

  destinations:
  - namespace: {{ $.Values.tenant.name }}
    name: {{ $binding.cluster }}

  clusterResourceWhitelist:
    - group: ""
      kind: ""

  namespaceResourceWhitelist:
    - group: ""
      kind: "Endpoints"
    - group: ""
      kind: "Pod"
    - group: ""
      kind: "ConfigMap"
    - group: ""
      kind: "Service"
    - group: "gateway.networking.k8s.io"
      kind: "HTTPRoute"
    - group: ""
      kind: "Secret"
    - group: ""
      kind: "ServiceAccount"
    - group: "discovery.k8s.io"
      kind: "EndpointSlice"
    - group: "apps"
      kind: "Deployment"
    - group: "apps"
      kind: "ReplicaSet"
    - group: "networking.k8s.io"
      kind: "Ingress"
    - group: "networking.k8s.io"
      kind: "NetworkPolicy"
    - group: "rbac.authorization.k8s.io"
      kind: "Role"
    - group: "rbac.authorization.k8s.io"
      kind: "RoleBinding"
    - group: "batch"
      kind: "Job"
    - group: "batch"
      kind: "CronJob"
    - group: "cilium.io"
      kind: "CiliumEndpoint"
    - group: "cert-manager.io"
      kind: "Certificate"
    - group: "cert-manager.io"
      kind: "CertificateRequest"
    - group: "acme.cert-manager.io"
      kind: "Order"
    - group: "storage.cnrm.cloud.google.com"
      kind: "StorageBucket"
    - group: "sql.cnrm.cloud.google.com"
      kind: "SQLUser"
    - group: "sql.cnrm.cloud.google.com"
      kind: "SQLDatabase"
    - group: "sql.cnrm.cloud.google.com"
      kind: "SQLInstance"
    - group: "iam.cnrm.cloud.google.com"
      kind: "IAMServiceAccount"
    - group: "iam.cnrm.cloud.google.com"
      kind: "IAMServiceAccountKey"
    - group: "iam.cnrm.cloud.google.com"
      kind: "IAMPartialPolicy"
    - group: "iam.cnrm.cloud.google.com"
      kind: "IAMPolicyMember"
    - group: "pubsub.cnrm.cloud.google.com"
      kind: "PubSubTopic"
    - group: "pubsub.cnrm.cloud.google.com"
      kind: "PubSubSubscription"
    - group: "pubsub.cnrm.cloud.google.com"
      kind: "PubSubSchema"
    - group: "policy"
      kind: "PodDisruptionBudget"
    - group: "example.crossplane.io"
      kind: "App"

  roles:
    - name: {{ $binding.role }}
      description: {{ printf "%s role" $binding.role | quote }}

      policies:
{{- range $policy := $role.policies }} 
{{- range $action := $policy.actions }}
        - p, proj:{{ $.Values.tenant.name }}-{{ $binding.role }}-{{ $binding.environmentPrefix }}:{{ printf "%s-%s-%s" $.Values.tenant.name $binding.role $binding.environmentPrefix }}, {{ $policy.resource }}, {{ $action }}, {{ $.Values.tenant.name }}/*, allow
{{- end }}
{{- end }}

      groups:
        - {{ printf "%s-%s-%s" $.Values.tenant.name $binding.role $binding.environmentPrefix | lower | quote }}

---
{{- end }}
