{{- range $cluster := $.Values.argocd.clusters }}
{{- range $role := $cluster.tenantAppProject.entraIDAppRoles }}

{{- $assign := $role.assignments | default dict }}
{{- $selectorEnabled := and $assign.principalObjectIdSelector $assign.principalObjectIdSelector.enabled }}
{{- $principals := $assign.principalObjectIds | default list }}

# --------------------------------------------------
# Group (Enterprise only)
# --------------------------------------------------
{{- if and (not $.Values.azure.freeTier) $selectorEnabled }}

apiVersion: groups.azuread.m.upbound.io/v1beta1
kind: Group
metadata:
  labels:
    prefix: {{ $cluster.environmentPrefix }}
    role: {{ $role.name }}
    tenant: {{ $.Values.tenant.name }}
  name: {{ $.Values.tenant.name }}-{{ $role.name }}-{{ $cluster.environmentPrefix }}
  namespace: crossplane
spec:
  forProvider:
    displayName: {{ $.Values.tenant.name | title }}-{{ $role.name | title }}-{{ $cluster.environmentPrefix | title }}
    securityEnabled: true
  providerConfigRef:
    name: azuread
    kind: ProviderConfig

---
{{- end }}

# --------------------------------------------------
# AppRole
# --------------------------------------------------
apiVersion: applications.azuread.m.upbound.io/v1beta1
kind: AppRole
metadata:
  labels:
    prefix: {{ $cluster.environmentPrefix }}
    role: {{ $role.name }}
    tenant: {{ $.Values.tenant.name }}
  name: {{ $.Values.tenant.name }}-{{ $role.name }}-{{ $cluster.environmentPrefix }}
  namespace: crossplane
spec:
  forProvider:
    allowedMemberTypes:
      - User
      - Group
    applicationId: {{ $.Values.argocd.entraAppId }}
    description: "{{ $role.name }} access for {{ $.Values.tenant.name }} in {{ $cluster.environmentPrefix }} environment"
    displayName: "{{ $.Values.tenant.name | title }} {{ $role.name | title }} {{ $cluster.environmentPrefix | title }}"
    value: {{ $.Values.tenant.name }}-{{ $role.name }}-{{ $cluster.environmentPrefix }}
  providerConfigRef:
    name: azuread
    kind: ProviderConfig

---
# --------------------------------------------------
# RoleAssignment
# --------------------------------------------------
{{- if and (not $.Values.azure.freeTier) $selectorEnabled }}

apiVersion: app.azuread.m.upbound.io/v1beta1
kind: RoleAssignment
metadata:
  name: {{ $.Values.tenant.name }}-{{ $role.name }}-{{ $cluster.environmentPrefix }}
  namespace: crossplane
spec:
  forProvider:
    appRoleIdRef:
      name: {{ $.Values.tenant.name }}-{{ $role.name }}-{{ $cluster.environmentPrefix }}

    principalObjectIdSelector:
      matchLabels:
        prefix: {{ $cluster.environmentPrefix }}
        role: {{ $role.name }}
        tenant: {{ $.Values.tenant.name }}

  providerConfigRef:
    name: azuread
    kind: ProviderConfig

---
{{- else }}

{{- range $i, $p := $principals }}

apiVersion: app.azuread.m.upbound.io/v1beta1
kind: RoleAssignment
metadata:
  name: {{ $.Values.tenant.name }}-{{ $role.name }}-{{ $cluster.environmentPrefix }}-{{ $i }}
  namespace: crossplane
spec:
  forProvider:
    appRoleIdRef:
      name: {{ $.Values.tenant.name }}-{{ $role.name }}-{{ $cluster.environmentPrefix }}

    principalObjectId: {{ $p | quote }}

  providerConfigRef:
    name: azuread
    kind: ProviderConfig

---
{{- end }}

{{- end }}

{{- end }}
{{- end }}
