{{- range $role := $.Values.tenant.rbac.roles }}
{{- range $instance := $role.instances }}

{{- $entra := $instance.entraID }}
{{- $assignment := $entra.assignment | default dict }}
{{- $selectorEnabled := and $assignment.principalObjectIdSelector $assignment.principalObjectIdSelector.enabled }}
{{- $principals := $assignment.principalObjectIds | default list }}

# --------------------------------------------------
# Group (Enterprise only)
# --------------------------------------------------
{{- if and (not $.Values.azure.freeTier) $selectorEnabled }}

apiVersion: groups.azuread.m.upbound.io/v1beta1
kind: Group
metadata:
  labels:
    prefix: {{ $instance.environmentPrefix }}
    role: {{ $role.name }}
    tenant: {{ $.Values.tenant.name }}
  name: {{ $.Values.tenant.name }}-{{ $role.name }}-{{ $instance.environmentPrefix }}
  namespace: crossplane
spec:
  forProvider:
    displayName: {{ $.Values.tenant.name | title }}-{{ $role.name | title }}-{{ $instance.environmentPrefix | title }}
    securityEnabled: true
  providerConfigRef:
    name: azuread
    kind: ProviderConfig

---
{{- end }}

# --------------------------------------------------
# AppRole
# --------------------------------------------------
{{- if not $entra.appRoleUUID }}
{{- fail (printf "Missing appRoleUUID for role '%s' in env '%s'" $role.name $instance.environmentPrefix) }}
{{- end }}

apiVersion: applications.azuread.m.upbound.io/v1beta1
kind: AppRole
metadata:
  labels:
    prefix: {{ $instance.environmentPrefix }}
    role: {{ $role.name }}
    tenant: {{ $.Values.tenant.name }}
  name: {{ $.Values.tenant.name }}-{{ $role.name }}-{{ $instance.environmentPrefix }}
  namespace: crossplane
spec:
  forProvider:
    roleId: {{ $entra.appRoleUUID | quote }}
    allowedMemberTypes: 
      - User
    applicationId: "/applications/{{ $.Values.tenant.rbac.entraArgoCDAppObjectId }}"
    description: "{{ $role.name }} access for {{ $.Values.tenant.name }} in {{ $instance.environmentPrefix }} environment"
    displayName: "{{ $.Values.tenant.name | title }} {{ $role.name | title }} {{ $instance.environmentPrefix | title }}"
    value: {{ $.Values.tenant.name }}-{{ $role.name }}-{{ $instance.environmentPrefix }}
  providerConfigRef:
    name: azuread
    kind: ProviderConfig

---
# --------------------------------------------------
# RoleAssignment
# --------------------------------------------------
# We use selector-based assignment for groups in enterprise tier, and direct principalObjectId assignment for users in free tier.
# In enterprise tier, the RoleAssignment will automatically assign the AppRole to the group that matches the specified labels.

{{- if and (not $.Values.azure.freeTier) $selectorEnabled }}

apiVersion: app.azuread.m.upbound.io/v1beta1
kind: RoleAssignment
metadata:
  name: {{ $.Values.tenant.name }}-{{ $role.name }}-{{ $instance.environmentPrefix }}
  namespace: crossplane
spec:
  forProvider:
    appRoleId: {{ $entra.appRoleUUID | quote }}
    resourceObjectId: {{ $.Values.tenant.rbac.entraArgoCDServicePrincipalObjectId | quote }}
    principalObjectIdSelector:
      matchLabels:
        prefix: {{ $instance.environmentPrefix }}
        role: {{ $role.name }}
        tenant: {{ $.Values.tenant.name }}
  providerConfigRef:
    name: azuread
    kind: ProviderConfig

---
# In enterprise tier we'll use the selector to assign roles to groups, so we don't need to create individual RoleAssignments for users.
# In free tier, since we can't assign roles to groups, we need to create RoleAssignments for individual users.
{{- else }}

{{- if and (not $.Values.azure.freeTier) (not $principals) }}
{{- fail (printf "No principalObjectIds provided for role '%s' in env '%s'" $role.name $instance.environmentPrefix) }}
{{- end }}

# {{- range $i, $p := $principals }}

apiVersion: app.azuread.m.upbound.io/v1beta1
kind: RoleAssignment
metadata:
  name: {{ $.Values.tenant.name }}-{{ $role.name }}-{{ $instance.environmentPrefix }}-{{ $i }}
  namespace: crossplane
spec:
  forProvider:
    appRoleId: {{ $entra.appRoleUUID | quote }}
    resourceObjectId: {{ $.Values.tenant.rbac.entraArgoCDServicePrincipalObjectId | quote }}
    principalObjectIdRef:
      name: {{ $.Values.tenant.name }}
      namespace: crossplane
    # principalObjectId: {{ $p | quote }}
  providerConfigRef:
    name: azuread
    kind: ProviderConfig

---
# {{- end }}

{{- end }}

{{- end }}
{{- end }}

{{- if $.Values.azure.freeTier }}

apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: "{{ $.Values.tenant.name }}-initial-password"
  namespace: crossplane
spec:
  length: 32

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ $.Values.tenant.name }}-initial-password"
  namespace: crossplane
spec:
  target:
    name: "{{ $.Values.tenant.name }}-initial-password"
  dataFrom:
    - sourceRef:
      - generatorRef:
          kind: Password
          name: "{{ $.Values.tenant.name }}-initial-password"

apiVersion: users.azuread.m.upbound.io/v1beta1
kind: User
metadata:
  labels:
    tenant: {{ $.Values.tenant.name }}
    environment-scope: "all"
    role: "developer"
    tier: "free"
  name: "{{ $.Values.tenant.name }}"
  namespace: crossplane
spec:
  forProvider:
    userPrincipalName: "{{ $.Values.tenant.name }}@rkaramadgmail.onmicrosoft.com"
    displayName: "{{ $.Values.tenant.name | title }}"
    passwordSecretRef:
      key: password
      name: "{{ $.Values.tenant.name }}-initial-password"
  providerConfigRef:
    name: azuread
    kind: ProviderConfig

{{- end }}
