tenant: null

# Example
# tenant:
#   name: pillow-factory
#   tenantShortName: pil
#   gcp:
#     aadGroupName: ACL.PLT.GCP.Tenant.PillowFactory
#     pushAuthorizedGithubRepos:
#       - jysk-dev/platform-demo-app-on-mvp
#       - jysk-dev/pil-goose-farm

# Upsert in environment values file. Permitted values: dev, test, prod.
environmentPrefix: ""

# The ID of the project where the clusters are located.
# This property is used to give the iam.workloadIdentityUser role to the Config Connector service accounts.
managementGoogleProjectId: kara-mgmt

# Must be pinned to prevent breaking changes caused by future Pod Security Standard updates, especially in production.
podSecurity:
  enforceVersion: v1.33

gateway:
  # This is the default GatewayClass created by Traefik chart.
  gatewayClass: "traefik"

  # Upsert in environment values file.
  loadBalancerIPs: []
