{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1" }}

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-local
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  provider:
    vault:
      server: "https://vault.mgmt.rezakara.demo"
      path: "local/shared"
      version: "v2"
      caProvider:
        type: Secret
        name: root-ca
        key: tls.crt
        namespace: platform-system
      auth: 
        kubernetes:
          mountPath: "{{ .Values.provider.vault.auth.kubernetes.mountPath }}"
          role: "external-secrets"
          serviceAccountRef:
            name: external-secrets
            namespace: platform-system

---
{{- end }}
