{{- if .Capabilities.APIVersions.Has "argoproj.io/v1alpha1/AppProject" }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-system
  namespace: argocd
spec:
  description: Project for tenant management.
  sourceRepos:
    - https://github.com/rezakaramad/kubepave
  destinations:
  - name:  in-cluster
    namespace: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
{{- end }}
