{{- if .Values.azureIdentity.enabled }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
  name: azure-sso
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-local
    kind: SecretStore
  target:
    name: argocd-secret 
    creationPolicy: Merge
  data:
    - secretKey: oidc.azure.clientSecret
      remoteRef:
        key: argocd/azure/sso
        property: client_secret

{{- end }}
