apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-org-rezakaramad
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: vault-local
    kind: SecretStore
  target:
    name: github-org-rezakaramad
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: https://github.com/rezakaramad
      mergePolicy: Merge
  data:
    - secretKey: githubAppID
      remoteRef:
        key: argocd/github/apps/rezakaramad
        property: app-id

    - secretKey: githubAppInstallationID
      remoteRef:
        key: argocd/github/apps/rezakaramad
        property: installation-id

    - secretKey: githubAppPrivateKey
      remoteRef:
        key: argocd/github/apps/rezakaramad
        property: private-key

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-org-talktorubberduckdev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: vault-local
    kind: SecretStore
  target:
    name: github-org-talktorubberduckdev
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: https://github.com/talktorubberduckdev
      mergePolicy: Merge
  data:
    - secretKey: githubAppID
      remoteRef:
        key: argocd/github/apps/talktorubberduckdev
        property: app-id

    - secretKey: githubAppInstallationID
      remoteRef:
        key: argocd/github/apps/talktorubberduckdev
        property: installation-id

    - secretKey: githubAppPrivateKey
      remoteRef:
        key: argocd/github/apps/talktorubberduckdev
        property: private-key

---
