{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1" }}

apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-local
  namespace: argocd
spec:
  provider:
    vault:
      server: "https://vault.mgmt.rezakara.demo"
      path: "local"
      version: "v2"
      caProvider:
        type: Secret
        name: root-ca
        key: tls.crt
        namespace: argocd
      auth:
        kubernetes:
          mountPath: {{ .Values.vaultAuth.mountPath | quote }}
          role: "eso-argocd"
          serviceAccountRef:
            name: argocd-server
            namespace: argocd

---
{{- end }}
