clusterSecretStore:
  enabled: true
  name: vault-local
  provider:
    vault:
      server: "https://vault.mgmt.rezakara.demo"
      path: "local"
      version: "v2"
      caProvider:
        type: Secret
        name: root-ca
        key: tls.crt
        namespace: platform-system
      auth:
        kubernetes:
          mountPath: ""  # overridden by values-local-management.yaml or values-local-workload.yaml
          role: "eso-shared"
          serviceAccountRef:
            name: external-secrets
            namespace: platform-system
