secretStore:
  scope: ''
  name: vault-local
  provider:
    vault:
      server: "https://vault.mgmt.rezakara.demo"
      path: "local"
      version: "v2"
      caProvider:
        type: Secret
        name: root-ca
        key: tls.crt
        namespace: platform-system
      auth: 
        kubernetes:
          mountPath: ''
          role: "external-secrets"
          serviceAccountRef:
            name: external-secrets
            namespace: platform-system
