clusterSecretStore:
  name: vault-local
  provider:
    vault:
      server: "https://openbao.mgmt.rezakara.demo"
      namespace: "platform"
      path: "kv"
      version: "v2"
      caProvider:
        type: Secret
        name: root-ca
        key: tls.crt
        namespace: platform-system

secretStore:
  name: vault-local
  provider:
    vault:
      server: "https://openbao.mgmt.rezakara.demo"
      namespace: "platform"
      path: "kv"
      version: "v2"
      caProvider:
        type: Secret
        name: root-ca
        key: tls.crt
        namespace: platform-system
