clusterSecretStore:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: "kubernetes-management"

secretStore:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: "kubernetes-management"
