clusterSecretStore:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: "kubernetes-workload"

secretStore:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: "kubernetes-workload"
