{{- if .Values.compositeResources.xTenantEntra.enabled }}

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xtenantentra
spec:
  compositeTypeRef:
    apiVersion: platform.jysk.tech/v1beta1
    kind: XTenantEntra
  mode: Pipeline
  pipeline:
    - step: run-the-template
      functionRef:
        name: xtenantentra
      input:
        apiVersion: defaults.fn.crossplane.io/v1beta1
        kind: XTenantEntraDefaults

        argocdApp:
          appRegObjectID: 805df85c-99e7-4e82-979f-242334735f59 # The ObjectID of the App Registration
          enterpriseAppObjectID: 622026ce-04e7-4b50-be99-f4302860da61 # The ObjectID of the Enterprise App

        # The provider config all resources should reference.
        providerConfigRef:
          name: azuread
          kind: ClusterProviderConfig

---
{{- end }}
