{{- if .Values.compositeResources.xTenantEntra.enabled }}

apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xtenantentras.idp.rezakara.demo
spec:
  group: idp.rezakara.demo
  names:
    kind: XTenantEntra
    plural: xtenantentras
  scope: Namespaced
  versions:
  - name: v1beta1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            type: object
          status:
            type: object
        required:
        - spec
        type: object
        x-kubernetes-validations:
        - message: metadata.name must be 3-21 chars, a valid RFC 1035 DNS label (lowercase
            letters, digits, hyphens; start with a letter and end alphanumeric)
          rule: self.metadata.name.size() >= 3 && self.metadata.name.size() <= 21
            && self.metadata.name.matches('^[a-z][a-z0-9-]*[a-z0-9]$')
    served: true

---
{{- end }}
