{{- if .Values.azureADProvider.enabled }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azuread
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: azure
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      mergePolicy: Replace
      data:
        credentials: |
          {
            "tenantId": "{{ `{{ .tenant_id }}` }}",
            "clientId": "{{ `{{ .client_id }}` }}",
            "clientSecret": "{{ `{{ .client_secret }}` }}",
            "environment": "public"
          }
  data:
    - secretKey: client_id
      remoteRef:
        key: crossplane/azure
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: crossplane/azure
        property: client_secret
    - secretKey: tenant_id
      remoteRef:
        key: crossplane/azure
        property: tenant_id

---
{{- end }}
