{{- if .Values.azureADProvider.enabled }}

apiVersion: azuread.m.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: azuread
  namespace: crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: crossplane-admin
      key: credentials

---
{{- end }}
