apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azuread
  namespace: keycloak
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: azuread
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: keycloak/azure/apps/keycloak
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: keycloak/azure/apps/keycloak
        property: client_secret
    - secretKey: tenant_id
      remoteRef:
        key: keycloak/azure/apps/keycloak
        property: tenant_id

---
