apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crossplane
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: crossplane
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      mergePolicy: Replace
      data:
        credentials: |
          {
            "client_id": "{{`{{ .client_id }}`}}",
            "client_secret": "{{`{{ .client_secret }}`}}",
            "url": "http://keycloak-service.keycloak.svc.cluster.local:8080",
            "realm": "master"
          }
  data:
    - secretKey: client_id
      remoteRef:
        key: keycloak/crossplane
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: keycloak/crossplane
        property: client_secret
