apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: keycloak-admin
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: keycloak/admin
        property: username
    - secretKey: password
      remoteRef:
        key: keycloak/admin
        property: password
