{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1" }}

apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  provider:
    {{- toYaml .Values.secretStore.provider | nindent 4 }}

---
{{- end }}
