apiVersion: v1
kind: ServiceAccount
metadata:
  name: bootstrap
  namespace: keycloak
  annotations:
    argo-cd.argoproj.io/sync-wave: "-10"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    argo-cd.argoproj.io/sync-wave: "-10"
