{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1" }}

apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-local
  namespace: platform-system
spec:
  provider:
    vault:
      server: "https://vault.mgmt.rezakara.demo"
      path: "local"
      version: "v2"
      caProvider:
        type: Secret
        name: root-ca
        key: tls.crt
        namespace: platform-system
      auth:
        kubernetes:
          mountPath: {{ .Values.vaultAuth.mountPath | quote }}
          role: "eso-platform-system"
          serviceAccountRef:
            name: external-secrets
            namespace: platform-system

---
{{- end }}
