{{- if .Capabilities.APIVersions.Has "argoproj.io/v1alpha1/Application" }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-application-folder
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-system
  source:
    repoURL: https://github.com/rezakaramad/kubepave
    targetRevision: HEAD
    path: argocd-applications/gcp
    directory:
      recurse: true
  destination:
    name:  in-cluster
    namespace: argocd
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/syncPolicy/automated
        - /spec/source/targetRevision
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true

---
{{- end }}

