{{- if .Capabilities.APIVersions.Has "argoproj.io/v1alpha1/AppProject" }}

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-system
spec:
  description: This AppProject is only used by the root application created.
  sourceRepos:
    - https://github.com/rezakaramad/kubepave
  destinations:
  - name:  in-cluster
    namespace: {{ .Release.Namespace }}
  namespaceResourceWhitelist:
  - group: argoproj.io
    kind: AppProject
  - group: argoproj.io
    kind: Application
  - group: argoproj.io
    kind: ApplicationSet

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-system
spec:
  description: Project for resources provisioned for each cluster.
  sourceRepos:
    - https://github.com/jysk-dev/platform-hub
    - https://github.com/jysk-dev/platform-valkey
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-system
spec:
  description: Project for tenant Argo CD resources.
  sourceRepos:
    - https://github.com/jysk-dev/platform-hub
    - https://github.com/jysk-dev/platform-tenants
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: ApplicationSet
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: repo.github.upbound.io
      kind: Repository
    - group: repo.github.upbound.io
      kind: RepositoryFile

---
{{- end }}
