apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: argocd-azure-identity
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp-kara-mgmt
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: oidc.azure.clientSecret
      remoteRef:
        key: argocd-azure-client-secret

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rezakaramad-github-organization
  namespace: argocd
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: gcp-kara-mgmt
    kind: ClusterSecretStore
  target:
    name: rezakaramad-github-organization
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: https://github.com/rezakaramad
      mergePolicy: Merge
  data:
    - secretKey: githubAppID
      remoteRef:
        key: argocd-github-rezakaramad-app-id
    - secretKey: githubAppInstallationID
      remoteRef:
        key: argocd-github-rezakaramad-installation-id
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: argocd-github-rezakaramad-private-key

---
