{{- if .Capabilities.APIVersions.Has "apiextensions.crossplane.io/v1/Composition" }}
{{- if .Values.xDeployment.enabled }}

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xdeployment

spec:
  compositeTypeRef:
    apiVersion: idp.rezakara.demo/v1beta1
    kind: XDeployment

  mode: Pipeline

  pipeline:
    - step: xdeployment
      functionRef:
        name: xdeployment
      input:
        apiVersion: platform.rezakara.demo/v1beta1
        kind: Input
        nextInsight:
          labelPrefix: "nextinsight.rezakara.demo/"

{{- end }}
{{- end }}
