{{- if .Values.xDeployment.enabled }}

{{- if .Capabilities.APIVersions.Has "pkg.crossplane.io/v1/Function" }}
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: xdeployment
spec:
  package: {{ required "xDeployment.providerPackage is required" .Values.xDeployment.providerPackage }}
  runtimeConfigRef:
    name: xdeployment

---
{{- end }}
{{- if .Capabilities.APIVersions.Has "pkg.crossplane.io/v1beta1/DeploymentRuntimeConfig" }}
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: xdeployment
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              env:
                - name: NEXTINSIGHT_BASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: nextinsight-credentials
                      key: url
                - name: NEXTINSIGHT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: nextinsight-credentials
                      key: token

---
{{- end }}
{{- end }}
