{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1" }}

# Each namespace will have its own SecretStore, which is used by ExternalSecrets to fetch secrets from the configured provider.

apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  provider:
    {{- toYaml .Values.secretStore.provider | nindent 4 }}

---
{{- end }}
