external-dns:
  fullnameOverride: external-dns

  logLevel: warning
  logFormat: json

  interval: 1m

  registry: txt

  txtPrefix: "externaldns"

  policy: sync

  sources:
    - gateway-httproute

  provider: ""

  env: {}

  extraArgs:
    - --publish-internal-services
