# In local setup, we use PowerDNS as the external DNS provider.
# The API key is stored in a Kubernetes secret
external-dns:
  provider: pdns

  env:
    - name: PDNS_API_KEY
      valueFrom:
        secretKeyRef:
          name: powerdns-api-key
          key: key
