bootstrap:
  image:
    repository: ghcr.io/rezakaramad/keycloak-bootstrap
    tag: sha-dd7c871

secretStore: 
  name: <upsert-in-env-values-file>
  provider: {}

entraId:
  tenantId: <upsert-in-env-values-file>
  syncMode: IMPORT
  groupMappings: []
