bootstrap:
  image:
    repository: ghcr.io/rezakaramad/kubepave-bootstrap
    tag: sha-073d789

secretStore: 
  name: ''
  provider: {}

entraId:
  tenantId: ''
  syncMode: IMPORT
  groupMappings: []
