entraId:
  tenantId: c6ba6fd6-0fdd-4458-ad98-0c292dd79188
  syncMode: IMPORT
  groupMappings:
    - name: azure-platform-admins
      aadGroupId: 9b207afe-3824-482f-8985-e2337a7f7e9b
      keycloakGroup: /platform-admins

secretStore:
  name: openbao-local
  provider:
    vault:
      auth:
        jwt:
          path: jwt-management
          role: keycloak
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: keycloak
              namespace: keycloak
            audiences:
              - https://kubernetes.default.svc.cluster.local
      caProvider:
        key: tls.crt
        name: root-ca
        namespace: keycloak
        type: Secret
      namespace: platform
      path: kv
      server: https://openbao.mgmt.rezakara.demo
      version: v2
