{{- if and .Values.secretStore.enabled (.Capabilities.APIVersions.Has "external-secrets.io/v1") }}

apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  provider:
    {{- toYaml .Values.secretStore.provider | nindent 4 }}

---
{{- end }}
