{{- if .Values.clusterSecretStore }}

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-kara-mgmt
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    gcpsm:
      projectID: kara-mgmt
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: external-secrets
            namespace: platform-system

---
{{- end }}
