{{- range $namespace := .Values.secretStoreNamespaces }}

apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-kara-mgmt
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    gcpsm:
      projectID: kara-mgmt
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: external-secrets
            namespace: platform-system

---
{{- end }}
