{{- range $namespace := .Values.secretStoreNamespaces }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-jysk-platform
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    gcpsm:
      projectID: jysk-platform
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: external-secrets
            namespace: platform-resources
{{- end }}
