apiVersion: v2
name: otelcol-cluster-collector
description: OpenTelemetry collector that ships Kubernetes events to Loki and kube-state-metrics to Mimir.
version: 0.0.1
dependencies:
  - name: opentelemetry-collector
    alias: otelCollector
    version: 0.175.1
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
