githubProvider:
  enabled: true

keycloakProvider:
  enabled: true

azureADProvider:
  enabled: true

secretStore:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes-workload
