selfSignedRootCA:
  # Set to false if the cluster uses an external CA provider (e.g. cloud PKI, Let's Encrypt, etc.).
  enabled: true

secretStore:
  name: vault-local
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: <upsert-in-env-values-file>
          role: crossplane
          serviceAccountRef:
            name: crossplane
            namespace: crossplane-system
      caProvider:
        key: tls.crt
        name: root-ca
        namespace: crossplane-system
        type: Secret
      path: local
      server: https://vault.mgmt.rezakara.demo
      version: v2
