githubProvider:
  enabled: false
  providerPackage: xpkg.upbound.io/crossplane-contrib/provider-upjet-github:v0.19.0
  activatedResources:
  - repositories.repo.github.m.upbound.io
  - repositoryfiles.repo.github.m.upbound.io

keycloakProvider:
  enabled: false
  providerPackage: xpkg.upbound.io/crossplane-contrib/provider-keycloak:v2.7.2

azureADProvider:
  enabled: false
  providerPackage: xpkg.upbound.io/upbound/provider-azuread:v2.2.1

tenantBootstrap:
  enabled: false

  functions:
    # xtenant render function package
    xtenantRender:
      providerPackage: ghcr.io/rezakaramad/function-xtenant-render:latest

    # xtenant validate function package
    xtenantValidate:
      providerPackage: ghcr.io/rezakaramad/function-xtenant-validate:latest

---
