selfSignedRootCA:
  # Set to false if the cluster uses an external CA provider (e.g. cloud PKI, Let's Encrypt, etc.).
  enabled: true

secretStore:
  name: openbao-local
  provider:
    vault:
      caProvider:
        key: tls.crt
        name: root-ca
        namespace: crossplane-system
        type: Secret
      namespace: platform
      path: kv
      server: https://openbao.mgmt.rezakara.demo
      version: v2
      auth:
        jwt:
          path: <upsert-in-env-values-file>
          role: crossplane
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: crossplane
              namespace: crossplane-system
            audiences:
              - https://kubernetes.default.svc.cluster.local

compositeResources:
  xTenantEntra:
    enabled: false
    packageTag: <upsert-in-env-values-file>

  xTenantArgo:
    enabled: false
    packageTag: <upsert-in-env-values-file>
