githubProvider:
  enabled: true
  providerPackage: xpkg.upbound.io/crossplane-contrib/provider-upjet-github:v0.19.0  

keycloakProvider:
  enabled: true
  providerPackage: xpkg.upbound.io/crossplane-contrib/provider-keycloak:v2.7.2

vaultProvider:
  enabled: true
  providerPackage: xpkg.upbound.io/upbound/provider-vault:v4.0.0
  agentImage: hashicorp/vault:1.19.0
  address: https://vault.vault.svc.cluster.local:8200
  caCertSecret: root-ca

entraIdProvider:
  enabled: true
  providerPackage: xpkg.upbound.io/upbound/provider-azuread:v2.2.1
  auth:
    method: secret
  activatedResources:
    - applications.applications.azuread.m.upbound.io
    - principals.serviceprincipals.azuread.m.upbound.io
    - approles.applications.azuread.m.upbound.io
    - roleassignments.app.azuread.m.upbound.io
    - federatedidentitycredentials.applications.azuread.m.upbound.io
    - groups.groups.azuread.m.upbound.io

secretStore:
  provider:
    vault:
      auth:
        jwt:
          path: jwt-management

compositeResources:
  xTenantEntra:
    enabled: true
    packageTag: v0.1.0

  xTenantArgo:
    enabled: true
    packageTag: v0.1.2
