secretStore:
  name: vault-local
  provider:
    vault:
      server: https://vault.mgmt.rezakara.demo
      path: local
      version: v2
      caProvider:
        type: Secret
        name: root-ca
        key: tls.crt
        namespace: backstage
      auth:
        jwt:
          path: jwt-management
          role: backstage
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: backstage
              namespace: backstage
            audiences:
              - https://kubernetes.default.svc.cluster.local

selfSignedRootCA:
  # Set to false if the cluster uses an external CA provider (e.g. cloud PKI, Let's Encrypt, etc.).
  enabled: true

backstage:
  backstage:
    appConfig:
      app:
        title: Backstage (Local)
        baseUrl: https://backstage.mgmt.rezakara.demo
      backend:
        baseUrl: https://backstage.mgmt.rezakara.demo
        cors:
          origin: https://backstage.mgmt.rezakara.demo
      auth:
        providers:
          microsoft:
            production:
              tenantId: c6ba6fd6-0fdd-4458-ad98-0c292dd79188

httpRoute:
  hostname: backstage.mgmt.rezakara.demo
