secretStore:
  name: openbao-local
  provider:
    vault:
      auth:
        jwt:
          path: jwt-management
          role: observability
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: observability
              namespace: observability
            audiences:
              - https://kubernetes.default.svc.cluster.local
      caProvider:
        key: tls.crt
        name: root-ca
        namespace: observability
        type: Secret
      path: kv
      server: https://openbao.mgmt.rezakara.demo
      version: v2
