{{- $tenant := .Values.tenant }}

{{/*
Create a Google service account for each tenant, 
which Config Connector later impersonates to manage that tenant’s cloud resources
*/}}

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: cc-{{ $tenant.name }}
  labels:
    {{- include "tpr.labels" . | nindent 4 }}
    platform.talktorubberduck.dev/tenant: {{ $tenant.name | lower }}
spec:
  displayName: Config Connector {{ $tenant.name | replace "-" " " | title }}
  description: Workload identity user for Config Connector in Kubernetes.

---
