apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-management
  namespace: argocd
spec:
  project: platform-system
  source:
    repoURL: https://github.com/rezakaramad/kubepave
    targetRevision: HEAD
    path: charts/external-secrets
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
        - values-local-management.yaml
  destination:
    name: in-cluster
    namespace: platform-system
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
