apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-system-management
  namespace: argocd
spec:
  project: platform-system
  source:
    repoURL: https://github.com/rezakaramad/kubepave
    targetRevision: HEAD
    path: charts/platform-system
  destination:
    name: in-cluster
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
