{{- if .Values.azureIdentity.enabled }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-5"
  name: azure-sso
  namespace: backstage
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao-local
    kind: SecretStore
  target:
    name: backstage-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTH_MICROSOFT_CLIENT_ID
      remoteRef:
        key: backstage/azure/app
        property: client_id
    - secretKey: AUTH_MICROSOFT_CLIENT_SECRET
      remoteRef:
        key: backstage/azure/app
        property: client_secret

---
{{- end }}
