apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    external-dns-create: "true"
  name: backstage
  namespace: backstage
spec:
  hostnames:
    - {{ .Values.httpRoute.hostname }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: default-traefik
      namespace: platform-system
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          {{- if .Values.oauth2Proxy.enabled }}
          name: oauth2-proxy
          port: 4180
          {{- else }}
          name: backstage
          port: 7007
          {{- end }}
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
