apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-5"
  name: msgraph-secrets
  namespace: backstage
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: msgraph-secrets
    creationPolicy: Owner
  data:
    - secretKey: MSGRAPH_CLIENT_ID
      remoteRef:
        key: backstage/msgraph/app
        property: client_id
    - secretKey: MSGRAPH_TENANT_ID
      remoteRef:
        key: backstage/msgraph/app
        property: tenant_id
    - secretKey: MSGRAPH_CLIENT_SECRET
      remoteRef:
        key: backstage/msgraph/app
        property: client_secret
