apiVersion: v2
name: lgtm-tempo
description: Grafana Tempo (traces backend), monolithic mode, storing blocks in SeaweedFS.
version: 0.0.1
dependencies:
  - name: tempo
    version: 1.24.4
    repository: https://grafana.github.io/helm-charts
