{{- if .Values.githubProvider.enabled }}
# This will allow Crossplane to create deployment repositories in 'fluxdojo' GitHub organization.

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crossplane-github-credentials-fluxdojo
  namespace: crossplane-system
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: {{ .Values.githubProvider.secretStoreRef.name }}
    kind: {{ .Values.githubProvider.secretStoreRef.kind }}
  target:
    name: crossplane-github-credentials-fluxdojo
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      mergePolicy: Replace
      data:
        credentials: |
          {
            "app_auth": [{
              "id": "{{`{{ .app_id }}`}}",
              "installation_id": "{{`{{ .installation_id }}`}}",
              "pem_file": {{`{{ .pem | toJson }}`}}
            }],
            "owner": "fluxdojo"
          }
  data:
    - secretKey: app_id
      remoteRef:
        key: crossplane/github/apps/org-fluxdojo
        property: app-id
    - secretKey: installation_id
      remoteRef:
        key: crossplane/github/apps/org-fluxdojo
        property: installation-id
    - secretKey: pem
      remoteRef:
        key: crossplane/github/apps/org-fluxdojo
        property: private-key

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crossplane-github-credentials-rezakaramad
  namespace: crossplane-system
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: {{ .Values.githubProvider.secretStoreRef.name }}
    kind: {{ .Values.githubProvider.secretStoreRef.kind }}
  target:
    name: crossplane-github-credentials-rezakaramad
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      mergePolicy: Replace
      data:
        credentials: |
          {
            "app_auth": [{
              "id": "{{`{{ .app_id }}`}}",
              "installation_id": "{{`{{ .installation_id }}`}}",
              "pem_file": {{`{{ .pem | toJson }}`}}
            }],
            "owner": "rezakaramad"
          }
  data:
    - secretKey: app_id
      remoteRef:
        key: crossplane/github/apps/org-rezakaramad
        property: app-id
    - secretKey: installation_id
      remoteRef:
        key: crossplane/github/apps/org-rezakaramad
        property: installation-id
    - secretKey: pem
      remoteRef:
        key: crossplane/github/apps/org-rezakaramad
        property: private-key

---
{{- end }}
