{{- if .Capabilities.APIVersions.Has "pkg.crossplane.io/v1/Function" }}
{{- if .Values.tenantBootstrap.enabled }}

apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-tenant-renderer
spec:
  package: {{ .Values.tenantBootstrap.functions.tenant.providerPackage }}
  runtimeConfigRef:
    name: function-tenant-renderer

---
{{- end }}
{{- if .Capabilities.APIVersions.Has "pkg.crossplane.io/v1beta1/DeploymentRuntimeConfig" }}
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: function-tenant-renderer
spec:
  deploymentTemplate:
    spec:
      selector: {} 
      template:
        spec:
          containers:
            - name: package-runtime
              env:
                - name: EXPORT_REPO_URL
                  value: "kubepave-tenants"
                - name: EXPORT_REPO_BRANCH
                  value: "main"
                - name: EXPORT_REPO_BASE_PATH
                  value: "tenants"
                - name: CROSSPLANE_NAMESPACE
                  value: "crossplane"
                - name: BASELINE_REPO_URL
                  value: "https://github.com/rezakaramad/kubepave.git"
                - name: BASELINE_REPO_BRANCH
                  value: "main"
                - name: BASELINE_REPO_BASE_PATH
                  value: "charts/baseline-tenant"
                - name: GITOPS_REPO_URL
                  value: "https://github.com/rezakaramad/kubepave.git"
                - name: GITOPS_REPO_BRANCH
                  value: "main"
                - name: GITOPS_REPO_BASE_PATH
                  value: "charts/gitops-tenant"

---
{{- end }}
{{- end }}
