{{- if .Capabilities.APIVersions.Has "pkg.crossplane.io/v1/Function" }}
{{- if .Values.tenantBootstrap.enabled }}

apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-tenant-renderer
spec:
  package: {{ .Values.tenantBootstrap.functions.tenant.providerPackage }}
  runtimeConfigRef:
    name: function-tenant-renderer

---
{{- end }}
{{- if .Capabilities.APIVersions.Has "pkg.crossplane.io/v1beta1/DeploymentRuntimeConfig" }}
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: function-tenant-renderer
spec:
  deploymentTemplate:
    spec:
      selector: {} 
      template:
        spec:
          containers:
            - name: package-runtime
              env:
                - name: PDNS_API_URL
                  value: "http://host.minikube.internal:5380/api/v1"
                - name: PDNS_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: powerdns-api-key
                      key: key
                - name: DNS_BASE_DOMAIN
                  value: "rezakara.demo"
                - name: EXPORT_REPO_URL
                  value: "kubepave-tenants"
                - name: EXPORT_REPO_BRANCH
                  value: "main"
                - name: EXPORT_REPO_BASE_PATH
                  value: "tenants"
                - name: CROSSPLANE_NAMESPACE
                  value: "crossplane"
                - name: WORKLOAD_CLUSTERS
                  value: "minikube-workload:wl"
                - name: BASELINE_REPO_URL
                  value: "kubepave"
                - name: BASELINE_REPO_BRANCH
                  value: "main"
                - name: BASELINE_REPO_BASE_PATH
                  value: "charts/baseline-tenant"
                - name: GITOPS_REPO_URL
                  value: "kubepave"
                - name: GITOPS_REPO_BRANCH
                  value: "main"
                - name: GITOPS_REPO_BASE_PATH
                  value: "charts/gitops-tenant"
                - name: ARGOCD_APP_ID
                  value: "6ebc7a2a-0d2c-4677-aebc-2b37371aca73"

---
{{- end }}
{{- end }}
