//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import runtime "k8s.io/apimachinery/pkg/runtime"

func (in *ClusterInput) DeepCopyInto(out *ClusterInput) {
	*out = *in
}

func (in *ClusterInput) DeepCopy() *ClusterInput {
	if in == nil {
		return nil
	}
	out := new(ClusterInput)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSInput) DeepCopyInto(out *DNSInput) {
	*out = *in
}

func (in *DNSInput) DeepCopy() *DNSInput {
	if in == nil {
		return nil
	}
	out := new(DNSInput)
	in.DeepCopyInto(out)
	return out
}

func (in *Input) DeepCopyInto(out *Input) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.DNS = in.DNS
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]ClusterInput, len(*in))
		copy(*out, *in)
	}
}

func (in *Input) DeepCopy() *Input {
	if in == nil {
		return nil
	}
	out := new(Input)
	in.DeepCopyInto(out)
	return out
}

func (in *Input) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
