apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-tenant-request-folder
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tenant-system
  source:
    repoURL: https://github.com/rezakaramad/kubepave-tenant-requests
    targetRevision: HEAD
    path: requests/
    directory:
      recurse: true
  destination:
    name:  in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
