{{- $tenant := .Values.tenant }}
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: {{ $tenant.name | lower }}
  labels:
    {{- include "tnr.labels" . | nindent 4 }}
    platform.talktorubberduck.dev/tenant: {{ $tenant.name | lower }}
spec:
  googleServiceAccount: "cc-{{ $tenant.name | lower }}@{{ .Values.managementGoogleProjectId }}.iam.gserviceaccount.com"
