#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"

# shellcheck source=libs/common.sh
source "$DIR/libs/common.sh"
# shellcheck source=libs/utils.sh
source "$DIR/libs/utils.sh"

POWERDNS_NAMESPACE="powerdns"
POWERDNS_CHART="$REPO_ROOT/charts/local/powerdns"

# Secrets file — generated on first run, never committed
SECRETS_FILE="$REPO_ROOT/.powerdns.env"

# systemd-resolved drop-in — routes *.rezakara.demo to PowerDNS from the host
RESOLVED_DROPIN_DIR="/etc/systemd/resolved.conf.d"
RESOLVED_DROPIN="$RESOLVED_DROPIN_DIR/rezakara.conf"


# -----------------------------------------------------------------------------
# Generate .powerdns.env on first run with random credentials.
# -----------------------------------------------------------------------------
init_secrets() {
  if [[ -f "$SECRETS_FILE" ]]; then
    return
  fi

  log "Generating PowerDNS secrets → $SECRETS_FILE"

  local db_password api_key

  db_password="$(openssl rand -base64 24 | tr -d '=')"
  api_key="$(openssl rand -base64 24 | tr -d '=')"

  cat > "$SECRETS_FILE" <<EOF
# Auto-generated by setup-dns.sh — DO NOT COMMIT
POWERDNS_DB_PASSWORD=${db_password}
POWERDNS_API_KEY=${api_key}
EOF

  chmod 600 "$SECRETS_FILE"

  ok "Secrets written to $SECRETS_FILE"
}

load_secrets() {
  if [[ ! -f "$SECRETS_FILE" ]]; then
    err "Secrets file not found: $SECRETS_FILE — run '$0 start' first"
    exit 1
  fi

  # shellcheck source=/dev/null
  source "$SECRETS_FILE"
}


# -----------------------------------------------------------------------------
# Create namespace and Kubernetes secrets in the management cluster
# -----------------------------------------------------------------------------
apply_k8s_secrets() {
  local context
  context="$(kind_context management)"

  log "Creating namespace $POWERDNS_NAMESPACE..."
  kubectl --context "$context" \
    create namespace "$POWERDNS_NAMESPACE" \
    --dry-run=client -o yaml | kubectl --context "$context" apply -f -

  log "Writing PowerDNS secrets to cluster..."

  kubectl --context "$context" \
    -n "$POWERDNS_NAMESPACE" \
    create secret generic powerdns-db-credentials \
    --from-literal=password="$POWERDNS_DB_PASSWORD" \
    --dry-run=client -o yaml | kubectl --context "$context" apply -f -

  kubectl --context "$context" \
    -n "$POWERDNS_NAMESPACE" \
    create secret generic powerdns-api-key \
    --from-literal=key="$POWERDNS_API_KEY" \
    --dry-run=client -o yaml | kubectl --context "$context" apply -f -

  ok "Secrets applied"
}


# -----------------------------------------------------------------------------
# Deploy PowerDNS via Helm into the management cluster
# -----------------------------------------------------------------------------
deploy_powerdns() {
  local context pdns_ip
  context="$(kind_context management)"
  pdns_ip="$(get_powerdns_ip)"

  log "Deploying PowerDNS to management cluster (node IP: $pdns_ip)..."

  # Adopt the namespace into Helm management in case it was created imperatively
  # by a prior failed run. Helm requires these to recognise the namespace as its own.
  kubectl --context "$context" annotate namespace "$POWERDNS_NAMESPACE" \
    meta.helm.sh/release-name=powerdns \
    meta.helm.sh/release-namespace="$POWERDNS_NAMESPACE" \
    --overwrite
  kubectl --context "$context" label namespace "$POWERDNS_NAMESPACE" \
    app.kubernetes.io/managed-by=Helm \
    --overwrite

  helm upgrade --install powerdns "$POWERDNS_CHART" \
    --kube-context "$context" \
    --namespace "$POWERDNS_NAMESPACE" \
    --timeout 5m \
    --wait

  ok "PowerDNS deployed"
}


# -----------------------------------------------------------------------------
# Wait for PowerDNS to answer DNS queries on the node IP
# -----------------------------------------------------------------------------
wait_for_powerdns_ip() {
  local pdns_ip
  pdns_ip="$(get_powerdns_ip)"

  log "Waiting for PowerDNS to answer on $pdns_ip:53..."

  for _ in {1..60}; do
    if dig @"$pdns_ip" rezakara.demo SOA +time=2 +tries=1 >/dev/null 2>&1; then
      ok "PowerDNS reachable at $pdns_ip:53"
      return 0
    fi
    sleep 2
  done

  err "Timed out waiting for PowerDNS"
  exit 1
}


# -----------------------------------------------------------------------------
# Write systemd-resolved drop-in to route *.rezakara.demo to PowerDNS from host.
# This is a one-time operation — the IP is fixed, so this never needs updating.
# -----------------------------------------------------------------------------
configure_resolved() {
  local pdns_ip
  pdns_ip="$(get_powerdns_ip)"

  local expected
  expected="$(cat <<EOF
[Resolve]
DNS=${pdns_ip}
Domains=~rezakara.demo
EOF
)"

  if sudo test -f "$RESOLVED_DROPIN" && \
     diff -q <(printf "%s\n" "$expected") <(sudo cat "$RESOLVED_DROPIN") >/dev/null 2>&1; then
    ok "systemd-resolved already configured"
    return
  fi

  log "Writing systemd-resolved drop-in → $RESOLVED_DROPIN"
  sudo mkdir -p "$RESOLVED_DROPIN_DIR"
  printf "%s\n" "$expected" | sudo tee "$RESOLVED_DROPIN" >/dev/null
  sudo systemctl restart systemd-resolved

  ok "systemd-resolved configured (*.rezakara.demo → $pdns_ip)"
}


# -----------------------------------------------------------------------------
# Remove systemd-resolved drop-in and restore default DNS
# -----------------------------------------------------------------------------
remove_resolved() {
  if sudo test -f "$RESOLVED_DROPIN"; then
    log "Removing systemd-resolved drop-in..."
    sudo rm -f "$RESOLVED_DROPIN"
    sudo systemctl restart systemd-resolved
    ok "systemd-resolved restored"
  else
    ok "systemd-resolved drop-in already absent"
  fi
}


start() {
  init_secrets
  load_secrets
  apply_k8s_secrets
  deploy_powerdns
  wait_for_powerdns_ip
  configure_resolved
}

reset() {
  remove_resolved

  local context
  context="$(kind_context management)"

  if kubectl --context "$context" get namespace "$POWERDNS_NAMESPACE" >/dev/null 2>&1; then
    log "Uninstalling PowerDNS..."
    helm uninstall powerdns \
      --kube-context "$context" \
      --namespace "$POWERDNS_NAMESPACE" || true
    kubectl --context "$context" \
      delete namespace "$POWERDNS_NAMESPACE" --ignore-not-found
    ok "PowerDNS removed"
  else
    ok "PowerDNS already absent"
  fi
}


case "${1:-start}" in
  start) start ;;
  reset) reset ;;
  *)
    echo "Usage: $0 [start|reset]"
    exit 1
    ;;
esac
