apiVersion: v1
kind: Service
metadata:
  name: powerdns-db
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: powerdns-db
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: powerdns-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  # headless — StatefulSet DNS resolution
