{{- if .Values.tenantBootstrap.enabled }}

{{- if .Capabilities.APIVersions.Has "pkg.crossplane.io/v1/Function" }}
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: xtenant-validate
spec:
  package: {{ required "tenantBootstrap.functions.xtenantValidate.providerPackage is required" .Values.tenantBootstrap.functions.xtenantValidate.providerPackage }}
  runtimeConfigRef:
    name: xtenant-validate

---
{{- end }}
{{- if .Capabilities.APIVersions.Has "pkg.crossplane.io/v1beta1/DeploymentRuntimeConfig" }}
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: xtenant-validate
spec:
  serviceAccountTemplate:
    metadata:
      name: xtenant-validate
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime

---
{{- end }}
{{- end }}
