apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextinsight-credentials
  namespace: crossplane
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: vault-local
    kind: ClusterSecretStore
  target:
    name: nextinsight-credentials
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: local/management/nextinsight
        property: url
    - secretKey: token
      remoteRef:
        key: local/management/nextinsight
        property: token
