apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics-development
  namespace: argocd
spec:
  project: platform-system
  source:
    repoURL: https://github.com/rezakaramad/kubepave
    targetRevision: HEAD
    path: charts/kube-state-metrics
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: kind-development
    namespace: observability
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
