apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-development
  namespace: argocd
spec:
  project: platform-system
  source:
    repoURL: https://github.com/rezakaramad/kubepave
    targetRevision: HEAD
    path: charts/traefik
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
        - values-local-development.yaml
  destination:
    name: kind-development
    namespace: platform-system
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
