{{- if .Capabilities.APIVersions.Has "identityprovider.keycloak.m.crossplane.io/v1alpha1/IdentityProviderMapper" }}

apiVersion: identityprovider.keycloak.m.crossplane.io/v1alpha1
kind: IdentityProviderMapper
metadata:
  name: azure-email
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  forProvider:
    realm: management
    identityProviderAlias: azure
    name: azure-email
    identityProviderMapper: oidc-user-attribute-idp-mapper

    extraConfig:
      syncMode: FORCE
      claim: email
      user.attribute: email

  providerConfigRef:
    kind: ProviderConfig
    name: keycloak

---

apiVersion: identityprovider.keycloak.m.crossplane.io/v1alpha1
kind: IdentityProviderMapper
metadata:
  name: azure-username
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  forProvider:
    realm: management
    identityProviderAlias: azure
    name: azure-username
    identityProviderMapper: oidc-user-attribute-idp-mapper

    extraConfig:
      syncMode: FORCE
      claim: preferred_username
      user.attribute: username

  providerConfigRef:
    kind: ProviderConfig
    name: keycloak

---

apiVersion: identityprovider.keycloak.m.crossplane.io/v1alpha1
kind: IdentityProviderMapper
metadata:
  name: azure-firstname
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  forProvider:
    realm: management
    identityProviderAlias: azure
    name: azure-firstname
    identityProviderMapper: oidc-user-attribute-idp-mapper

    extraConfig:
      syncMode: FORCE
      claim: given_name
      user.attribute: firstName

  providerConfigRef:
    kind: ProviderConfig
    name: keycloak

---

apiVersion: identityprovider.keycloak.m.crossplane.io/v1alpha1
kind: IdentityProviderMapper
metadata:
  name: azure-lastname
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  forProvider:
    realm: management
    identityProviderAlias: azure
    name: azure-lastname
    identityProviderMapper: oidc-user-attribute-idp-mapper

    extraConfig:
      syncMode: FORCE
      claim: family_name
      user.attribute: lastName

  providerConfigRef:
    kind: ProviderConfig
    name: keycloak

---

{{- range .Values.entraId.groupMappings }}
apiVersion: identityprovider.keycloak.m.crossplane.io/v1alpha1
kind: IdentityProviderMapper
metadata:
  name: {{ .name }}
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  forProvider:
    realm: management
    identityProviderAlias: azure
    name: {{ .name }}
    identityProviderMapper: oidc-advanced-group-idp-mapper

    extraConfig:
      syncMode: FORCE
      claim: groups
      claim.value: {{ .aadGroupId }}
      group: {{ .keycloakGroup }}

  providerConfigRef:
    kind: ProviderConfig
    name: keycloak

---
{{- end }}
{{- end }}