apiVersion: oidc.keycloak.m.crossplane.io/v1alpha1
kind: IdentityProvider
metadata:
  name: azure
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "45"
spec:
  forProvider:
    realm: management
    alias: azure
    displayName: Azure AD
    enabled: true
    trustEmail: true

    authorizationUrl: https://login.microsoftonline.com/{{ .Values.entraId.tenantId }}/oauth2/v2.0/authorize
    tokenUrl: https://login.microsoftonline.com/{{ .Values.entraId.tenantId }}/oauth2/v2.0/token
    userInfoUrl: https://graph.microsoft.com/oidc/userinfo
    jwksUrl: https://login.microsoftonline.com/{{ .Values.entraId.tenantId }}/discovery/v2.0/keys
    issuer: https://login.microsoftonline.com/{{ .Values.entraId.tenantId }}/v2.0
    logoutUrl: https://login.microsoftonline.com/{{ .Values.entraId.tenantId }}/oauth2/v2.0/logout

    defaultScopes: "openid profile email"
    syncMode: {{ .Values.entraId.syncMode }}

    extraConfig:
      clientAuthMethod: "client_secret_post"
      sendIdTokenOnLogout: "true"
      sendClientIdOnLogout: "false"

    clientIdSecretRef:
      name: azuread
      key: client_id
    clientSecretSecretRef:
      name: azuread
      key: client_secret

  providerConfigRef:
    kind: ProviderConfig
    name: keycloak

---
