selfSignedRootCA:
  # Set to false if the cluster uses an external CA provider (e.g. cloud PKI, Let's Encrypt, etc.)
  enabled: true
  # Create the 'selfsigned' ClusterIssuer + 'root-ca' Certificate on management cluster
  mint: true
