selfSignedRootCA:
  # Set to false if the cluster uses an external CA provider (e.g. cloud PKI, Let's Encrypt, etc.)
  enabled: false

# Only one Google service account (GSA) should be create for cert-manager.
# Using workload identity all cert-manager instances use the same GSA.
createIamServiceAccount: true

hostedZoneName: mgmt.gcp.talktorubberduck.dev
