selfSignedRootCA:
  # Set to false if the cluster uses an external CA provider (e.g. cloud PKI, Let's Encrypt, etc.)
  enabled: true
  # In development clusters, we don't mint a root CA; we copy it from management via 'setup-trust.sh'.
  mint: false
