apiVersion: v2
name: otelcol-node-collector
description: OpenTelemetry collector that runs on every node and ships pod logs, host metrics and kubelet stats to Loki and Mimir.
version: 0.0.1
dependencies:
  - name: opentelemetry-collector
    alias: otelCollector
    version: 0.175.1
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
