createIamServiceAccount: true

configConnectorContext:
  enabled: true

githubProvider:
  enabled: true

entraIdProvider:
  enabled: true
  clientID: 14819823-b8ff-408a-8dd9-41b5d703af14
  activatedResources:
    - applications.applications.azuread.m.upbound.io
    - principals.serviceprincipals.azuread.m.upbound.io
    - approles.applications.azuread.m.upbound.io
    - roleassignments.app.azuread.m.upbound.io
    - federatedidentitycredentials.applications.azuread.m.upbound.io
    - groups.groups.azuread.m.upbound.io

compositeResources: {}
