apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otelcol-cluster-collector-management
  namespace: argocd
spec:
  project: platform-system
  source:
    repoURL: https://github.com/rezakaramad/kubepave
    targetRevision: HEAD
    path: charts/otelcol-cluster-collector
    helm:
      valueFiles:
        - values.yaml
        - values-local-management.yaml
  destination:
    name: in-cluster
    namespace: observability
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
