apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pingkaf-management
  namespace: argocd
spec:
  project: platform-system
  source:
    repoURL: https://github.com/rezakaramad/kubepave
    targetRevision: HEAD
    path: charts/pingkaf
  destination:
    name: in-cluster
    namespace: kafka-system
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
