{{- if .Values.githubProvider.enabled }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-rezakaramad-org
  namespace: crossplane-system
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: gcp-kara-mgmt
    kind: ClusterSecretStore
  target:
    name: github-app-rezakaramad-org
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      mergePolicy: Replace
      data:
        credentials: |
          {
            "app_auth": [{
              "id": "{{`{{ .app_id }}`}}",
              "installation_id": "{{`{{ .installation_id }}`}}",
              "pem_file": {{`{{ .pem | toJson }}`}}
            }],
            "owner": "rezakaramad"
          }
  data:
    - secretKey: app_id
      remoteRef:
        key: crossplane-github-rezakaramad-app-id
    - secretKey: installation_id
      remoteRef:
        key: crossplane-github-rezakaramad-installation-id
    - secretKey: pem
      remoteRef:
        key: crossplane-github-rezakaramad-private-key

{{- end }}
