{{- if .Values.githubProvider.enabled }}

apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: github-rezakaramad
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: {{ .Values.githubProvider.providerPackage }}

{{- end }}
