tenant: null

gcp:
  # The billing account to set the projects to use.
  billingAccountId: "01AB18-BBE5BC-76F96B"

  # The GCP project ID of the Shared VPC host project.
  # Tenant projects are attached to this as service projects.
  sharedVpcHostProjectID: kara-shared

  # The GCP project ID where the GKE cluster runs.
  # Used to construct the Workload Identity pool name (<project>.svc.id.goog) in the
  # IAMPartialPolicy that allows the 'cert-manager' Kubernetes SA to impersonate the GCP SA.
  managementGoogleProjectID: kara-mgmt

  # The GCP project number where the Workload Identity Pool is located.
  managementGoogleProjectNumber: "1048890523970"

  # The environment prefix can be no longer than 9 characters without being truncated.
  # Used to name tenant Google projects under the 'Tenant Environments' folder
  # in the format: <tenant-name>-<environment-prefix>
  tenantEnvironments:
    - prefix: wl # Immutable, cannot be changed
      folderId: "377346212838" # Immutable, cannot be changed
      # Roles granted to the tenant Google group for WL environment
      tenantGroupRoles:
        - roles/viewer
        - roles/storage.admin
        - roles/pubsub.admin
        - roles/memorystore.admin

argocd:
  clusters:
    - clusterName: gke-workload
      environmentPrefix: wl
      tenantAppProject:
        policies:
          - resource: applications
            actions:
              - get
              - update
              - delete
              - sync
              - action/apps/Deployment/pause
              - action/apps/Deployment/resume
              - action/apps/Deployment/restart
              - action/batch/CronJob/create-job
          - resource: logs
            actions:
              - get
