secretStore:
  name: gcp-secret-manager
  provider:
    gcpsm:
      projectID: kara-mgmt
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: external-secrets
            namespace: platform-system

# ------------------------------------------------------------------------------
# -- Argo CD managed clusters
# ------------------------------------------------------------------------------
# ArgoCD is using Workload Identity and where therefore there are not secrets in the credentials.
clusterCredentials:
  - name: gke-development
    server: "" # Put here the GKE cluster API server URL (e.g. https://<IP_ADDRESS>)
    environmentPrefix: dev

# ------------------------------------------------------------------------------
# -- Argo CD main configs
# ------------------------------------------------------------------------------
argocd:
  # Argo CD server
  server:
    httproute:
      hostnames:
        - argocd.gcp.talktorubberduck.dev

    grpcroute:
      hostnames:
        - argocd.gcp.talktorubberduck.dev

    volumeMounts:
      - name: azure-token
        mountPath: "/var/run/secrets/tokens/"
        readOnly: true

    volumes:
      - name: azure-token
        projected:
          sources:
            - serviceAccountToken:
                audience: api://AzureADTokenExchange
                expirationSeconds: 3600
                path: azure-token

    env:
      - name: AZURE_FEDERATED_TOKEN_FILE
        value: /var/run/secrets/tokens/azure-token

    # Server metrics service configuration
    metrics:
      enabled: true

    # GCP Workload Identity binding for the argocd-server service account
    # Used when adding and managing GKE clusters in Argo CD
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: "argocd@kara-mgmt.iam.gserviceaccount.com"

  # Argo CD Controller
  controller:
    # GCP Workload Identity binding for the argocd-application-controller service account
    # Used when syncing applications to GKE clusters
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: "argocd@kara-mgmt.iam.gserviceaccount.com"

  # Enable ApplicationSet in any namespace feature
  applicationSet:
    allowAnyNamespace: true

  # General Argo CD configuration
  # Any values you put under `.configs.cm` are passed to argocd-cm ConfigMap.
  configs:
    cm:
      url: https://argocd.gcp.talktorubberduck.dev


# -------------------------------------------------------------------------------
# -- GitOps platform
# -------------------------------------------------------------------------------
# Git source for all ArgoCD application manifests and Helm charts.
repoURL: https://github.com/rezakaramad/kubepave

applicationFolder:
  path: argocd-applications/gcp
