apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-mgmt
  namespace: argocd
spec:
  project: platform-system
  source:
    repoURL: https://github.com/rezakaramad/kubepave
    targetRevision: HEAD
    path: charts/gcp/crossplane
    helm:
      valueFiles:
        - values-mgmt.yaml
  destination:
    name: in-cluster
    namespace: crossplane-system
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
    - RespectIgnoreDifferences=true
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
