apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-platform-resources-management
  namespace: argocd
spec:
  project: platform-system
  source:
    repoURL: https://github.com/rezakaramad/kubepave
    targetRevision: HEAD
    path: charts/gcp/tenant-platform-resources
  destination:
    name: in-cluster
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
