{{- if .Values.entraIdProvider.enabled }}

apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azuread
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: {{ .Values.entraIdProvider.providerPackage }}
  runtimeConfigRef:
    name: provider-azuread

{{- end }}
